### ISSUE TITLE
How can I get http response status code when I use Handle() method?

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/WebApiClient#10]
As following code shown:

```
var proxy = HttpApiClient.Create<IMyInterace>();
var result = await proxy.CallRemoteApiAsync( ... )
    .Handle().WhenCatch<Exception>(e => {
        // do something

        return new SomeResult { 
            StatusCode = ????.StatusCode,
            Message = "Some message",
            Success = false
        };
    });
```

When I create `SomeResult`, I need a given status code from HttpClient encapsulated within HttpApiClient. How can I get such status code?

**Comment by xljiulang** [comment]
针对不少开发者都提到这个问题，目前在库里加入了HttpFailureStatusException异常，需要在ApiReturnAttribute设置EnsureSuccessStatusCode属性为true才生效。
另外，如果想捕获其它更多内容，需要开发者派生相应的ApiReturnAttribute，加入自己的业务异常，然后在Handle()里处理异常。

**Comment by alexinea** [comment]
I have implemented a return-attribute derived from ApiReturnAttribute by myself to solve this requirement.

thx a lot :)
