### ISSUE TITLE
如果API需要OAuth授权，需要做哪些前置工作或者配置

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/WebApiClient#11]

**Comment by xljiulang** [comment]
可以给接口写个ApiActionFilterAttribute，在OnBeginRequestAsync方法请求获取Access Token，设置到context.HttpApiConfig.HttpClient.DefaultRequestHeaders.Authorization

**Comment by xljiulang** [comment]
现在WebApiClient已经内置一个OAuthTokenFilter的全局过滤器抽象类，继承这个类，实现token获取和token刷新功能，很方便的对接OAuth。您可以使用WebApiClient自带的TokenClient类来获取和刷新Token，也可以自己实现。
