### ISSUE TITLE
本地地址设置代理无效

### ISSUE THREAD

**Issue by lindenrty2** [dotnetcore/WebApiClient#110]
本地地址设置代理无效,希望能增加本地地址的代理设定(例如系统自带的BypassProxyOnLocal)设置

**Comment by xljiulang** [comment]
HttpClient对于localhost或回环ip永远是不生效，你可以使用局域网ip或机器名

**Comment by lindenrty2** [comment]
不是localhost，经过测试目前192.x，10.x系列的局域网保留IP都不会起作用。
系统自带的API有BypassProxyOnLocal这个属性来决定是否针对局域网开启代理功能。

**Comment by xljiulang** [comment]
问题不在webApiClient层，在HttpClient层就是这样的效果。

**Comment by lindenrty2** [comment]
目前测试下来局域往只有使用机器名才生效，WCF那套东西测试下来也有同样问题，按理说不应该是这样的效果才对。

**Comment by xljiulang** [comment]
最有可能是winnet层的

**Comment by lindenrty2** [comment]
但是作为Windows的全局代理设定，这个是起作用的
