### ISSUE TITLE
啥时候支持一下非json格式的嵌套类型和数组参数

### ISSUE THREAD

**Issue by liaowubinf** [dotnetcore/WebApiClient#114]
WebApiClient已经用的很顺手了，很喜欢这种设计，但是碰到如题这种接口的时候就很难受， 因为webapiclient不支持， 我知道作者之前说过更复杂的类型应考虑用json方式传递， 奈何提供接口的是别人呀， 人家只支持form方式你也没法左右不是，目前是通过过滤器的方式手动拆开复杂类型参数， 还是希望能够得到原生的支持， 谢谢了！
PS:我看refit项目有人提过类似的工单， 而且被作者采纳，现在支持了😂

**Comment by xljiulang** [comment]
数据参数支持了OpenApi 定义的5种方式

**Comment by xljiulang** [comment]
你可以把问题描述清楚一点，相信有好办法解决

**Comment by liaowubinf** [comment]
> 你可以把问题描述清楚一点，相信有好办法解决

就是声明Parameter的Dto里面如果嵌套了另一个Dto或List<Dto>,  希望得到的效果是 A.B.c=xxx或A.B[0].c=xxx, 目前是不支持的，但是这样的场景却很多， 我用webapiclient以来已经遇到好几次了

**Comment by xljiulang** [comment]
这个可以考虑在KeyValue序列化上作扩展支持

**Comment by xljiulang** [comment]
@liaowubinf 
基于Utf8JsonReader，这个自定义功能太简单了

**Comment by xljiulang** [comment]
现在可以通过以下方式来配置启用这个功能，默认是ShortName
```
// 注册userApi
services.AddHttpApi<IUserApi>(o =>
{
    o.KeyValueSerializeOptions.KeyNamingStyle = KeyNamingStyle.FullName;
});
```

**Comment by liaowubinf** [comment]
> 现在可以通过以下方式来配置启用这个功能，默认是ShortName
> 
> ```
> // 注册userApi
> services.AddHttpApi<IUserApi>(o =>
> {
>     o.KeyValueSerializeOptions.KeyNamingStyle = KeyNamingStyle.FullName;
> });
> ```

这个是core版才有对吧， 以前的版本不会支持了是吗 @xljiulang

**Comment by xljiulang** [comment]
是的，core版才有
