### ISSUE TITLE
有什么方案可以快速从refit转换为webapiclient吗

### ISSUE THREAD

**Issue by litliang-cn** [dotnetcore/WebApiClient#115]
如题

**Comment by xljiulang** [comment]
这个切换工作量很小的，接口声明都是差不多的。切换之后，就多了自定义特性的切面能力，或者甚至你甚至可以在原来的refit接口上添加webaiclient的特性，让一个接口在能保持原refit调用的情况下，又能webapiclient调用

**Comment by litliang-cn** [comment]
我的意思就是那些attribute,一个一个回去加太多啦。。有没有什么方式可以快速转换。。

**Comment by xljiulang** [comment]
或者可以通过openapi文档反向生成代码
