### ISSUE TITLE
ApiFilterAttribute支持构造函数注入吗？

### ISSUE THREAD

**Issue by csabc** [dotnetcore/WebApiClient#120]
`    public class SignFilterAttribute : ApiFilterAttribute
    {
        private readonly IConfiguration _configuration;
        public SignFilterAttribute(IConfiguration configuration)
        {
            _configuration = configuration;
        }`

ApiFilterAttribute和ApiActionFilterAttribute有什么不一样，执行顺序吗？谢谢！

**Comment by xljiulang** [comment]
两个特性在两个不同分支

**Comment by csabc** [comment]
好像不支持构造函数注入 ServiceFilter 和TypeFilter不能修饰接口。
如果想在请求的头加一个自定义的字段，字段值从配置文件读取，应该怎么做？

**Comment by xljiulang** [comment]
好好看文档就知道了

**Comment by xljiulang** [comment]
所有服务获取都是context.HttpContext.ServiceProvider获取即可

**Comment by hjkl950217** [comment]
@csabc  特性是比较特殊的一类群体，他会在程序早期初始化，官方也要求他的构造方法参数是常量(你使用特性时就发现不能使用new这个关键字了)
