### ISSUE TITLE
不兼容Newtonsoft.Json.JsonIgnore

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/WebApiClient#121]
我看了一下注册接口时的json配置是使用系统自带的json序列化库，但我们因为历史原因不能切换到`System.Json`。请问如何配置让webapiClient支持`Newtonsoft.Json`下面的特性呢？如果必须使用`System.Json`,则会带来额外的学习成本和风险，这是团队近期不能接受的。

期望在我们系统中统一使用`Newtonsoft.Json`，询问如何配置？

**Comment by hjkl950217** [comment]
或者，能不能我我自己在项目中将`WebApiClient`序列化的部分整体替换为`Newtonsoft.Json`？ 如果可以，我需要修改或配置那里？

**Comment by xljiulang** [comment]
可以实现json序列化的接口，然后注册到服务里

**Comment by hjkl950217** [comment]
请问是那一个接口呢？没有找到

**Comment by xljiulang** [comment]
依赖的服务都在这里：https://github.com/dotnetcore/WebApiClient/blob/master/WebApiClientCore/Microsoft.Extensions/DependencyInjection/HttpApiExtensions.cs

**Comment by hjkl950217** [comment]
好的，非常感谢！ 平时有时间来搜索这些东西，最近太忙了，感谢感谢！
顺便给这个库点个赞！ 比官方推荐的`Refit `不知道高到那里去了。
