### ISSUE TITLE
看了一遍README，不是特别明白

### ISSUE THREAD

**Issue by tonyqus** [dotnetcore/WebApiClient#124]
麻烦请教下，这个库比微软官方的HttpClientFactory好在哪？不是特别明白

**Comment by xljiulang** [comment]
WebApiClient-->HttpClientFactory-->HttpClient，他们的依赖关系是这样子，HttpClient是网络请求的核心，HttpClientFactory用于管理HttpClient的创建与生命周期管理，WebApiClient是声明式的Http调用框架。试问，HttpClientFactory比HttpClient好在哪，它能取代HttpClient吗？

**Comment by hjkl950217** [comment]
HttpClientFactory用于管理HttpClient的创建与生命周期管理
HttpClient是网络请求的核心
官方库中使用的还是HttpClient进行操作，但是他有这么几个不够好的地方：
1.  响应体需要自己写代码序列化
2.  使用起来还有一点繁琐
3.  不是声明式使用

WebApiClient内部还是使用的官方库，只是用声明式的方式让使用它更加方便。
