### ISSUE TITLE
建议：增加Cache的描述和灵活性

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/WebApiClient#125]
Cache特性经过测试，默认是按`url`中的`host+path`部分当做缓存的key，但是首页的`readme`中没有说明,仅在`CacheAttribute`类上有说明，我提一点建议：

针对说明:
1.  原来的`CacheAttribute` 修改为`CacheByUrlAttribute`
2. `readme`中更新说明，在文档上说明是用什么做缓存的key

针对Key规则：
1. 将`CacheAttribute`类中的`var uri = request.RequestUri.ToString();` 这个获取key的代码做成方法，子类可重写。这样可以在项目中按自己需要开发`CacheByAbsoluteUrlAttribute` 、 `CacheByPathAttribute` 等特性，增加灵活性
2. 另一个方案是增加全局的key构建规则

上面几点只是我的一点想法，可以讨论讨论，应该比较简单，回头我来贡献这个代码都阔以。

**Comment by xljiulang** [comment]
[Cache]是[ApiCache]的一个具体实现的子类，它实现了基类的GetCacheKeyAsync()方法，其实现依赖于Uri和Header。
同理，你需要的CacheByXXXAttribute，只需要从[ApiCache]实现即可。

**Comment by hjkl950217** [comment]
这样也可以。描述上我更新了一下，是为了在项目中可以按需要自己开发`CacheByXXX`。
我又仔细看了下2个类，如果要开发`CacheByXXX`，确实自己从`ApiCache`中继承是比较好的方式，继承`Cache`反而搞复杂了。

描述上是不是可以更新一下，让用的人从`readme`中直接直接，当URL和header一样时才会被缓存？我是自己阅读源代码知道的

**Comment by hjkl950217** [comment]
另外我看到了新添加的json.net的支持，但它不是默认选项，每次都要自己添加特性比较麻烦。 是否允许我上次的PR那样直接全局替换？ 在许多.net core 3.1的项目中，依然有许多项目组选择使用json.net而不是system.text.json

**Comment by hjkl950217** [comment]
#126

**Comment by xljiulang** [comment]
Api的设计，不是说改就改类型名称，兼容性必须确保高版本兼容低版本，所以修改CacheAttribute的名称是得不偿失的，当然，你若要丰富readme的文档，欢迎你的提交来丰富文档。

**Comment by hjkl950217** [comment]
已经提交文档的PR了。这里完善下说明即可~
.net core和.net framework自带的API响应缓存默认是用全部URL当Key，这里我测试时发现不是，所以才有这个疑问的。文档上面完善了就可以了~

**Comment by xljiulang** [comment]
thank you!已合并。
