### ISSUE TITLE
发送 http post 请求，但是 query里面也有参数，这种如何写？

### ISSUE THREAD

**Issue by MrBenWang** [dotnetcore/WebApiClient#127]
请问，参数在 url 中 和 body 中同时存在的 奇葩 api，该怎么写:

post http://xx.com/api/login?UID=123&Version=3.0.1

body:
{
    "UserName":"username",
    "Password":"dc483e80a7a0bd9ef71d8cf973673924"
}

**Comment by xljiulang** [comment]
对于post方式请求，openApi的描述参数可以为：query参，path参，form参或body参，这里不是api奇葩，可能是你对http或webApiClient还没有详细地去理解

**Comment by MrBenWang** [comment]
@xljiulang 谢谢你的回复，我阅读 wiki 中 [WebApiClient基础-2.4Query参数](https://github.com/dotnetcore/WebApiClient/wiki/WebApiClient%E5%9F%BA%E7%A1%80#24-query%E5%8F%82%E6%95%B0)
没有找到，可以区分参数 FromBody 和 FromQuery 的样例。

请问，有这样的功能，或者其他实现方法吗？
比如web api中的:  public bool Todo([FromQuery] Version, [FromBody] UserInfo _user);

**Comment by xljiulang** [comment]
你可能喜欢[Parameter]特性
