### ISSUE TITLE
希望能增加获取 HttpHost 的委托

### ISSUE THREAD

**Issue by qianmingjun1001** [dotnetcore/WebApiClient#128]
有的场景下是通过服务发现与注册服务去拿要请求服务的真实地址，所以 HttpHost 本身不能写死在程序里，所以希望增加一个可以获取 HttpHost 的委托

**Comment by xljiulang** [comment]
[HttpHostAttribute]是一种方便的host编译时配置，除此之外，还有HttpApiOptions定义的HttpHost属性，当配置了HttpHost属性值，会自动覆盖[HttpHostAttribute]值。HttpApiOptions的配置不需要编译时确定，而是运行时配置，具体请看readme文档或Microsoft.Extensions.Options文档。

**Comment by xljiulang** [comment]
对于微服务集成，可以考虑在DelegatingHandler做全局处理，也可以在WebApiClientCore写一个自定义ApiFilterAttribute来实现，无非是将请求地址更换而已。

**Comment by qianmingjun1001** [comment]
这样做也可以
