### ISSUE TITLE
我自定义了一个接口继承IHttpApi，但是没办法声明属性

### ISSUE THREAD

**Issue by wulienen** [dotnetcore/WebApiClient#129]
引用的nuget包是WebApiClient.JIT 版本1.1.4
我自定义了一个接口继承IHttpApi，但是没办法声明属性
![image](https://user-images.githubusercontent.com/26619474/91022622-0d091200-e628-11ea-83dc-19d3ad333605.png)

**Comment by xljiulang** [comment]
不允许声明属性

**Comment by wulienen** [comment]
好吧。。我想    _httpApi.接口方法 的时候，往 _httpApi.Claims里边塞点东西。。既然不行的话我只能另想办法了。

**Comment by xljiulang** [comment]
通过服务提供者来获取

**Comment by wulienen** [comment]
> 通过服务提供者来获取

好的谢谢，我再研究下
