### ISSUE TITLE
批量调用报错，程序集中有重复的类型名。

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/WebApiClient#13]
在 System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
   在 System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
   在 System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   在 System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent)
   在 WebApiClient.HttpApiClientProxy.ImplementAsHttpApiClient(Type interfaceType, MethodInfo[] apiMethods)
   在 System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   在 WebApiClient.HttpApiClientProxy.CreateProxyWithInterface(Type interfaceType, IApiInterceptor interceptor)
   在 WebApiClient.HttpApiClient.Create[TInterface](HttpApiConfig httpApiConfig)
   在 Doc.LabelTypeMapper.Add(LabelType t) 位置 C:\Users\Administrator\Documents\Visual Studio 2015\Projects\百美\__SCHEMA\PackingSlip\Ｋ【软件】项目源代码\2.0\Document\LabelTypeMapper.cs:行号 48
   在 SDK.FedEx.ExpressDomesticShipClient.ExpressDomesticShipService_ReplySuccess(ProcessShipmentReply reply) 位置 C:\Users\Administrator\Documents\Visual Studio 2015\Projects\百美\__SCHEMA\PackingSlip\Ｋ【软件】项目源代码\2.0\SDK\FedEx\ExpressDomesticShipClient.cs:行号 44
   在 SDK.FedEx.BaseShipClient.Reply() 位置 C:\Users\Administrator\Documents\Visual Studio 2015\Projects\百美\__SCHEMA\PackingSlip\Ｋ【软件】项目源代码\2.0\SDK\FedEx\BaseShipClient.cs:行号 134

**Comment by xljiulang** [comment]
哪个版本的

**Comment by hzr1348** [comment]
1.1.6

**Comment by hzr1348** [comment]
项目框架4.5.2

**Comment by xljiulang** [comment]
在1.1.6版本，这是一个已知的非线程安全静态方法，更新到1.1.7就可以解决此问题。
