### ISSUE TITLE
建议提供完善的英文文档，并申请加入.net 基金会项目

### ISSUE THREAD

**Issue by athinboy** [dotnetcore/WebApiClient#130]
希望可以成为.net基金会项目。
https://dotnetfoundation.org/projects
https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md

**Comment by xljiulang** [comment]
认真做好项目应该做的内部功能，是当下（也包括未来）要做的最主要事情，我们希望项目能够服务于更多需要的人，同时也希望有更多人来一起完善项目的点点滴滴。

**Comment by athinboy** [comment]
@xljiulang 
申请为.net基金会项目，会提升使用量。更多的项目使用才能 收集更多的改进意见，从而不断优化。
而且国外dotnet开发更多些。我认为提供良好的英文文档也是有益的。

**Comment by xljiulang** [comment]
@athinboy 
那也需要从脚下做起，你也帮帮忙出一份力，文档和代码都可以
