### ISSUE TITLE
Support asp.net core attribute

### ISSUE THREAD

**Issue by pengweiqhca** [dotnetcore/WebApiClient#131]
Any plans to support Microsoft.AspNetCore.Mvc.HttpXXXAttribute, Microsoft.AspNetCore.Mvc.FromXXXAttribute, etc？

**Comment by xljiulang** [comment]
WebApiClient不依赖于asp.netcore，所以自然无法识别asp.netcore的特性类型。
但WebApiClient内置了[Parameter]特性，使用方式为[Parameter(Kind.Query)]、[Parameter(Kind.Form)]和[Parameter(Kind.JsonBody)]等，与[FromXXX]使用方式是相似。
