### ISSUE TITLE
使用非autofac依赖注册环境

### ISSUE THREAD

**Issue by GlodenBoy** [dotnetcore/WebApiClient#132]
我是在WPF中使用的，并且用了Prism的框架，该框架在某个版本抛弃了autofac 使用了Unity。

我按照WIKI中autofac 注册方式拼接了一个类似的。
![image](https://user-images.githubusercontent.com/2329528/92886094-f515f880-f445-11ea-9f38-f7390a136215.png)

但是到最后一步我只能注册RegisterInstance 才能匹配 InstancePerHttpRequest(); 的写法，并且能正常使用，但是我觉得请求应该用Instance 不太合适，所有的注册方法如下，请问我使用Unity该如何注册webApiClient？

![image](https://user-images.githubusercontent.com/2329528/92886310-21ca1000-f446-11ea-8ed3-13ab20605e86.png)

**Comment by xljiulang** [comment]
把注册为HttpApiFactory<>注册为IHttpApiFactory<>，这是单例；
然后取出IHttpApiFactory<>，创建接口实例，这是瞬态；
遵循这个原则即可。

**Comment by GlodenBoy** [comment]
> 把HttpApiFactory<>注册为IHttpApiFactory<>，这是单例；
> 然后取出IHttpApiFactory<>，创建接口实例，这是瞬态；
> 遵循这个原则即可。

![image](https://user-images.githubusercontent.com/2329528/92900115-fc430380-f451-11ea-94c7-3060bdab723c.png)


谢谢老哥，查询了下资料，发现可以取基础容器进行注册，按照老哥的说法，注册成瞬态如图，应该行了吧...

**Comment by xljiulang** [comment]
看样子没错，虽然没用过Unity

**Comment by GlodenBoy** [comment]
> 看样子没错，虽然没用过Unity

感谢老哥 抽空回复，大哥大气
