### ISSUE TITLE
控制台或者窗体应用程序怎么注入服务呀？

### ISSUE THREAD

**Issue by ZhaoYis** [dotnetcore/WebApiClient#133]
如题

**Comment by xljiulang** [comment]
自己new ServiceCollection()，把服务（窗体也是服务）注册到ServiceCollection，然后BuildServiceProvider()，即可得到根IServiceProvider。从IServiceProvider里获取MainFrom，MainFrom构造器注入它依赖的其它服务，然后就可以一路跑了。
