### ISSUE TITLE
注册的Api更新Cookie的问题

### ISSUE THREAD

**Issue by Cyaim** [dotnetcore/WebApiClient#135]
请求的接口非常不幸的使用了Cookie保存身份信息，
服务器Cookie2个小时自动过期，请问在代码中如何手动更新CookieContainer?

![image](https://user-images.githubusercontent.com/28213262/95934982-bee0e580-0e04-11eb-817a-59ce283bd9d9.png)

目前使用了HttpApiConfig对DefaultRequestHeaders做设置，但是Register返回的工厂实例不便于保存和操作。

**Comment by xljiulang** [comment]
cookie过期之后的响应，有特定的http状态码吗，比如401等？

**Comment by Cyaim** [comment]
服务器处理后仍然响应200，在响应内容里有授权失败等信息

**Comment by xljiulang** [comment]
可以编写DelegatingHandler来做响应处理，分析响应为授权失败的话，就在当次请求里做登录与重新请求操作。可以部分参考：https://github.com/dotnetcore/WebApiClient/blob/master/WebApiClientCore.Extensions.OAuths/HttpMessageHandlers/OAuthTokenHandler.cs

**Comment by Cyaim** [comment]
3Q,我康康~

**Comment by xljiulang** [comment]
@Cyaim 刚刚增加一个CookieAuthorizationHandler类，可以满足解决这样的场景，下面是使用说明：

https://github.com/dotnetcore/WebApiClient/blob/master/README.md#cookie%E8%BF%87%E6%9C%9F%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0

**Comment by Cyaim** [comment]
大佬流批，
不过但并不是所有的接口服务鉴权都会返回401，能不能提供一个入口让编码者来决定是否需要重新登录呢？

**Comment by xljiulang** [comment]
重写IsUnauthorizedAsync(HttpResponseMessage)

**Comment by Cyaim** [comment]
OK~
