### ISSUE TITLE
Webapiclientcore 如何应用JWT

### ISSUE THREAD

**Issue by Yuanxw612** [dotnetcore/WebApiClient#137]
Webapiclientcore 如何应用JWT接口验证，以及如何支持角色策略？
文档缺失的厉害，上手有点懵

**Comment by xljiulang** [comment]
JWT是一种凭证的格式，对于客户端，甚至不需要解决，如同cookie一样，提交给服务端就行。当然，如果你想了解JWT如何颁发和验证，如果与OAuth2结合， 这是服务端要掌握的概念。

**Comment by Yuanxw612** [comment]
我困惑的是如何设置 jwt token，以及刷新，这一块的文档内容有点少

**Comment by xljiulang** [comment]
https://github.com/dotnetcore/WebApiClient#oauthstoken
