### ISSUE TITLE
需要临时保存PathQueryAttribute和HttpContentAttribute生成的查询串和请求体

### ISSUE THREAD

**Issue by hubo0831** [dotnetcore/WebApiClient#138]
可以在后续管道特性中计算签名，请考虑增强相关方法，
如在PathQueryAttribute中修改CreateUri方法加入参数ApiParameterContext context，可以把 keyValues放在context.Properties中

**Comment by xljiulang** [comment]
除了PathQueryAttribute，还有其它地方需要类似的功能吗

**Comment by xljiulang** [comment]
已经为它增加SerializeToKeyValues虚方法，(FormContentAttribute与FormDataContentAttribute本身已有此方法)见https://github.com/dotnetcore/WebApiClient/commit/9aec427ab81a3a233e969850603b883af0b8f643

**Comment by hubo0831** [comment]
HttpContentAttribute也需要

**Comment by xljiulang** [comment]
HttpContentAttribute是个abstract类，没有实现

**Comment by hubo0831** [comment]
JsonContentAttribute和XmlContentAttribute，其实我觉得放在基类更好些

**Comment by xljiulang** [comment]
JsonContentAttribute和XmlContentAttribute怎么有keyValue

**Comment by hubo0831** [comment]
需要临时保存body

**Comment by xljiulang** [comment]
更新到 1.1.3，已增加相关功能

**Comment by hubo0831** [comment]
好的，谢谢
