### ISSUE TITLE
ApiResponseStatusException获取RequestMessage的content抛异【资源被释放】

### ISSUE THREAD

**Issue by aabb1212** [dotnetcore/WebApiClient#141]
1.继承ExceptionFilterAttribute，重写OnExceptionAsync方法获取context.Exception的内部异常(循环取内部异常，直到内部异常为null)
2.判断该内部异常是否是ApiResponseStatusException
3.如果是ApiResponseStatusException，则执行exception.ResponseMessage.RequestMessage.Content.ReadAsStringAsync()；
4.RequestMessage.Content抛异
【Cannot access a disposed object.Object name: 'WebApiClientCore.HttpContents.JsonContent'.】

如果我想获取到content的信息，我需要怎么操作呢

**Comment by xljiulang** [comment]
只有在请求前获取请求信息的内容。
