### ISSUE TITLE
可否增加Parameter特性HostAttribute，方便运行时切换Host

### ISSUE THREAD

**Issue by huangjia2107** [dotnetcore/WebApiClient#144]
1.实际项目中，存在运行时动态切换Host的需要；
2.目前是利用UriAttribute将uri完全参数化，然后给接口增加扩展方法，只将Host作为扩展方法参数；
建议：可否在Parameter特性中增加HostAttribute

```
[HttpGet("/api/v1.0/info")]
Task<string> Get([Host] string host);
```

这样可以使用参数中指定的Host进行请求。

**Comment by xljiulang** [comment]
开发者自己定义HostAttribute就行。

**Comment by huangjia2107** [comment]
已经实现完了，谢谢了
