### ISSUE TITLE
Post请求能否支持IEnumerable<KeyValuePair<string, string>>

### ISSUE THREAD

**Issue by tianxin8206** [dotnetcore/WebApiClient#145]
发送Post请求，传输application/x-www-form-urlencoded格式的数据时，如果key较少，创建一个类感觉挺麻烦的，能不能像FormUrlEncodedContent直接传IEnumerable<KeyValuePair<string, string>>类型的参数？

**Comment by xljiulang** [comment]
你试试就知道了。

**Comment by xljiulang** [comment]
实际上，匿名类型，Dictionary<string, string>，IEnumerable<KeyValuePair<string, string>>，甚至FormUrlEncodedContent，都可以做为参数

**Comment by tianxin8206** [comment]
@xljiulang 尝试过了，服务端接收不到参数，换成对象就好了

**Comment by xljiulang** [comment]
不用看服务端，看客户端提交了什么数据。[LoggingFilter]

**Comment by tianxin8206** [comment]
@xljiulang 你好，客户端提交的内容格式为 Key=xxx&Value=xxx，和FormUrlEncodedContent不一致

**Comment by xljiulang** [comment]
增加了IEnumerable<KeyValuePair<string, string>>的支持：https://github.com/dotnetcore/WebApiClient/commit/ba277b4b22846412af31df5917dedd8aafe1b778

**Comment by xljiulang** [comment]
v1. 1. 4已支持
