### ISSUE TITLE
Core版怎么不支持AliasAs写在实体参数里面了

### ISSUE THREAD

**Issue by liaowubinf** [dotnetcore/WebApiClient#146]
我的参数比较多，我想把参数封装到一个实体里面， 然后在实体属性上加AliasAs，发现core版不支持这样了， 要怎么弄？

**Comment by xljiulang** [comment]
[JsonPropertyName]

**Comment by liaowubinf** [comment]
get请求也用这个是吧， 我试试

**Comment by liaowubinf** [comment]
core版的不是自动跳转的吗， 之前都用的老版， 新版很多配置都不一样了
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to

**Comment by liaowubinf** [comment]
可以了，谢谢
