### ISSUE TITLE
[JsonFormField]不能修饰实体参数类型的属性

### ISSUE THREAD

**Issue by liaowubinf** [dotnetcore/WebApiClient#147]
比如 我有一个这样的接口   url?a=[1,2,3]&b=1&c=2&d=3&e=["a","b","c"],  我把这些参数封装成了一个实体，那参数a和参数e该怎么传过去呢？

**Comment by xljiulang** [comment]
[JsonFormField]属于webApiClient的参数特性，只能修饰接口参数。

**Comment by liaowubinf** [comment]
那我这种情况只能把 a和e作为接口的参数独立出来然后用 [JsonFormField]修饰， 对吧

**Comment by xljiulang** [comment]
[JsonFormField]会把参数json序列化得到的文本放到表单里面，而不是当作url的query

**Comment by liaowubinf** [comment]
哦哦， 那有没有针对get请求的这种畸形接口的手段呢

**Comment by xljiulang** [comment]
[PathQuery]特性

**Comment by liaowubinf** [comment]
> [PathQuery]特性

我的意思是 PathQuery 怎么传递 json 数组

**Comment by xljiulang** [comment]
需要你自行处理

**Comment by liaowubinf** [comment]
> 需要你自行处理

好的，我先自行处理， 建议CollectionFormat能加一个枚举项来处理这个😆

**Comment by xljiulang** [comment]
你应该实现自定义特性，用于完成特殊场景的需求
