### ISSUE TITLE
如何通过ApiRequestContext 获取 form表单的内容

### ISSUE THREAD

**Issue by liaowubinf** [dotnetcore/WebApiClient#152]
我自定义了一个ApiActionAttribute，想通过ApiRequestContext拿到form表单的内容再加密， 
发现context.HttpContext.RequestMessage.Content  为null， 需要怎么获取呢

**Comment by xljiulang** [comment]
你可以使用过滤器，或者继承formcontent特性来实现加密

**Comment by xljiulang** [comment]
> 执行前顺序

参数值验证 -> IApiActionAttribute -> IApiParameterAttribute -> IApiReturnAttribute -> IApiFilterAttribute

**Comment by liaowubinf** [comment]
好的， 谢谢！
