### ISSUE TITLE
不能自动带上原请求的请求头

### ISSUE THREAD

**Issue by bingxueyinlian** [dotnetcore/WebApiClient#155]
请问一下，现在不能自动带上原请求的请求头吗？

**Comment by xljiulang** [comment]
原请求指的是什么

**Comment by bingxueyinlian** [comment]
@xljiulang 就是我前端浏览器调用的API的时候请求头里带了一些参数，比如header["aaa"]="AAA";
后台接收到请求，再转发给其他API地址时，这个请求头丢失了。
比如：前台浏览器带请求头直接调用的服务A的Controller，这个时候是能取到请求头数据的。如果服务A的Controller通过以下方式，调用了服务B的方法。服务B接收的请求头里是没有浏览器调用时携带的请求头的。
```
public interface IUserApi
{
    [HttpPost("api/users")]
    Task<User> PostAsync(User user);
}
```

**Comment by xljiulang** [comment]
这个组件不是用于反向代理的
