### ISSUE TITLE
建议取消对MemoryCache的直接依赖

### ISSUE THREAD

**Issue by Harbour8643** [dotnetcore/WebApiClient#159]
官方有Memory、SQL Server、Redis三种缓存，并不是所有项目都会用Memory，有时候想统一缓存到Redis等其他中。

**Comment by xljiulang** [comment]
WebApiClient抽象层没有哪个接口依赖内存缓存，你指的是哪个接口或抽象类型？

**Comment by Harbour8643** [comment]
WebApiClientCore 依赖了Microsoft.Extensions.Caching.Memory，这是内存缓存的实现；建议改为依赖Microsoft.Extensions.Caching.Abstractions的IDistributedMemoryCache，对比Microsoft对Session的实现，其也需要缓存，却是依赖的IDistributedMemoryCache，其好处是，当项目中Session、Cookie、其他组件等需要用缓存时，项目可以统一使用一种缓存，例如放Redis中，只需在项目中手动添加services.AddStackExchangeRedisCache()。

**Comment by xljiulang** [comment]
WebApiClientCore是实现层，为什么不能依赖Microsoft.Extensions.Caching.Memory，如果IDistributedMemoryCache，WebApiClientCore拿什么来实现。

**Comment by Harbour8643** [comment]
好吧，可以看看asp.net core 的Session实现，也是实现层，其核心依赖就是基于IDistributedMemoryCache缓存，至于IDistributedMemoryCache的实现，由用户决定通过DI注入什么实现，比如Microsoft.Extensions.Caching.Memory对IDistributedMemoryCache，还有其他的，这是由使用者决定的。
eg：
services.AddDistributedMemoryCache();//分布式缓存，启用session必须有IDistributedMemoryCache的实现类services.AddSession(option =>//开启session服务
{
     option.Cookie.Name = "RAMSCore.Session";
     option.IdleTimeout = TimeSpan.FromHours(2);//Session有效时间是两个小时
});

**Comment by xljiulang** [comment]
对于默认实现的DefaultResponseCacheProvider，它是IResponseCacheProvider的一个内存实现，IResponseCacheProvider本身就设计为类似IDistributedMemoryCache，只包含缓存操作的两个Get和Set方法，引入IDistributedMemoryCache反正像是踢皮球，让人一头雾水，自己实现一个xxCacheResponseCacheProvider，就可以替换DefaultResponseCacheProvider。Session它不一样，缓存只是它复杂业务里面的一个小小功能，去掉缓存，它还有很多不可替换的功能，但IResponseCacheProvider本身就可以整体替换。
