### ISSUE TITLE
Post方式传送base64报错

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#16]
`[HttpPost("/api/AliMarket/OcrIdCard")]
 ITask<ResultModel<OcrIdCardResult>> OcrIdCard(string FaceBase64Image, string BackBase64Image);`

错误提示:
UriFormatException: Invalid URI: The Uri string is too long.
System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)
System.Uri..ctor(string uriString)
WebApiClient.Attributes.PathQueryAttribute.UsePathQuery(Uri uri, IEnumerable<KeyValuePair<string, string>> keyValues)
WebApiClient.Attributes.PathQueryAttribute+<BeforeRequestAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApiClient.Contexts.ApiActionContext+<PrepareRequestAsync>d__27.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApiClient.ApiTask+ApiTaskOf+<RequestAsync>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
CHY.BusinessService.UserService.Service.UserBaseSerivce+<OcrIdCard>d__12.MoveNext() in UserBaseSerivce.cs

**Comment by bao2314483** [comment]
post方式不应该是参数放在url里面啊

**Comment by xljiulang** [comment]
所有默认参数对应请求的Query参数，如果POST提交，请参考wiki里的WebApiClient基础：使用POST提交

**Comment by bao2314483** [comment]
问题反馈真快

**Comment by hjkl950217** [comment]
@bao2314483  麻烦老哥关闭一下issue
