### ISSUE TITLE
设置请求响应内容 GZip 自动解压缩

### ISSUE THREAD

**Issue by hd2y** [dotnetcore/WebApiClient#161]
参考：[HttpClientHandler.AutomaticDecompression Property](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.automaticdecompression?view=netcore-3.1)

在新版中 `AutomaticDecompression ` 属性默认为 `None`，需要在使用时先进行设置。

> For the .NET Framework 4.x System.Net.Http binary in the Global Assembly Cache (GAC), the default value is None.  
> When the System.Net.Http NuGet package v4.1.0 to v4.3.2 is used, the default is GZip and Deflate.  
> After NuGet package v4.3.2, the default value of None is used.

需要调整以下代码：

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpApi<IUserApi>();
}
```

修改为：

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpApi<IUserApi>()
       .ConfigurePrimaryHttpMessageHandler(c =>
           new HttpClientHandler()
           {
               AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate
           }
       );
}
```

感谢 QQ 群大佬的答疑解惑，这里补提 Issue 方便后续其他有同样问题的小伙伴参考。

**Comment by zhangkeyuan** [comment]
刚到遇到这个问题
