### ISSUE TITLE
返回类型Task<string>的字符串会自动加上双引号

### ISSUE THREAD

**Issue by mushramb0** [dotnetcore/WebApiClient#162]
`[HttpGet("api/value")]
public Task<string> GetAsync();`
如上接口返回的是xxx字符串,但是程序读到的是"xxx",多了个双引号,加上RawReturnAttribute也没有作用,请问怎么处理

**Comment by xljiulang** [comment]
你看看服务器的响应内容，包括引号，是不是刚好等于响应头的content-length值

**Comment by mushramb0** [comment]
> 你看看服务器的响应内容，包括引号，是不是刚好等于响应头的content-length值

content-length的值不包括双引号

**Comment by xljiulang** [comment]
postman请求看看输出

**Comment by mushramb0** [comment]
> postman请求看看输出

原来是Accept-Encoding的问题 谢谢了
