### ISSUE TITLE
自定义枚举converter，添加到KeyValueSerializeOptions.Converters没有生效

### ISSUE THREAD

**Issue by zhaoqinghai** [dotnetcore/WebApiClient#165]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 
**Additional context**

**Comment by xljiulang** [comment]
当类型为如下时，直接转换为文本处理，你可以让你的枚举继承byte或int16类型。
```
typeCode == TypeCode.String ||
typeCode == TypeCode.Int32 ||
typeCode == TypeCode.Decimal ||
typeCode == TypeCode.Double ||
typeCode == TypeCode.Single
```
