### ISSUE TITLE
是否可以提供运行时修改http请求上下文的机制？

### ISSUE THREAD

**Issue by personball** [dotnetcore/WebApiClient#166]
需求场景如下：

服务A调用服务B，在不提前对 `IUserApi` 做任何Attribute修饰的情况下，可以通过委托添加统一的自定义请求头，比如传递 currentUser、 currentTenant、cultureName、impersonatorUser 等等信息。由于是固定的框架性的请求附带信息，放入参描述显得请求参数和赋值动作非常不DRY

或者是否有其他拓展入口？

**Comment by xljiulang** [comment]
Attribute不是简单的功能标记，相反，Attribute是一个执行切面，任何动态或不动态的信息，都可以在Attribute的请求前或请求后方法里添加到context中。

**Comment by personball** [comment]
> Attribute不是简单的功能标记，相反，Attribute是一个执行切面，任何动态或不动态的信息，都可以在Attribute的请求前或请求后方法里添加到context中。

明白了，所以我上述需求其实可以通过attribute实现，ioc注入所需的资源，对context进行操作即可？
谢谢回复。
