### ISSUE TITLE
请教一个问题，相同的接口，多个URL轮番调用，应该怎么处理？

### ISSUE THREAD

**Issue by coolincy** [dotnetcore/WebApiClient#168]
例如：有3个http接口服务，它们提供的接口方法是一样的，业务需要对以上不同的接口服务进行调用。
AddHttpApi<THttpApi>方法貌似只能单例，有没有在调用接口时替换掉接口URL的方法？

非Core版本原来是可以根据不同URL直接Resolve出不同的实例。Core版本好像没了这个方法了。

**Comment by xljiulang** [comment]
[Uri]参数特性传Uri，或者你继承声明出三个接口来注册。

**Comment by xljiulang** [comment]
如果你的功能是类似于客户端负载均衡，那自己写个MyHostAttribute:HttpHostBaseAttribute来实现拾取Uri并设置到上下文的请求内容Uri就好了。
