### ISSUE TITLE
请教一个问题，请求头的值可以设置为动态的吗

### ISSUE THREAD

**Issue by aion1998** [dotnetcore/WebApiClient#169]
就是我想在我程序的任何一个环节去修改这个请求的请求头的值，这样的话我该咋配置这个请求头
![image](https://user-images.githubusercontent.com/19725014/122635454-9b4e0780-d116-11eb-9b26-b43a462ca1ee.png)

**Comment by xljiulang** [comment]
把值放到参数来，然后继续用[Header]特性来修饰这个参数。
