### ISSUE TITLE
参数加了MulitpartContent问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#17]
` [HttpPost("/api/UserBasicInfo/BindCredentials")]
        ITask<ResultModel<UserBasicInfoResult>> BindCredentials([MulitpartContent]Guid Id,[MulitpartContent]string CredentialsBackImg);`

API接口接收CredentialsBackImg的值:
http%3a%2f%2fbaseservice%3a8104%2f%2fImgTemp%2f636616463453653498.jpg

有什么办法可以API接收能变回正常

**Comment by bao2314483** [comment]
`[HttpPost("/api/UserBasicInfo/BindCredentials")]
        ITask<ResultModel<UserBasicInfoResult>> BindCredentials([MulitpartContent]UserBasicInfoBindCredentialsReq Data);`

我改成用类模型传送过去,api接收还是跟上面一样,值被编码了

**Comment by bao2314483** [comment]
我看了源码发现MulitpartTextContent 这个类型,对值进行
`HttpUtility.UrlEncode(value, Encoding.UTF8);`编码了
我觉得这个设定会不会不合理,因为MulitpartText肯定是post提交的,只有get提交才需要编码

**Comment by xljiulang** [comment]
谢谢发现了这个问题，你的代码已经应用到最新的1.2.2版本。

**Comment by bao2314483** [comment]
还担心你不采纳

**Comment by bao2314483** [comment]
还担心你不采纳
