### ISSUE TITLE
WebApiClientCore.OpenApi.SourceGenerator 报错

### ISSUE THREAD

**Issue by frisktale** [dotnetcore/WebApiClient#170]
命令 ： WebApiClientCore.OpenApi.SourceGenerator.exe -o D:\openapi.json
错误：Unhandled exception. System.AggregateException: One or more errors occurred. (Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri'))
全部错误信息截图：
![image](https://user-images.githubusercontent.com/21367674/122792403-b8d4ca00-d2ec-11eb-8ac1-3639516c0862.png)
generator版本：
![image](https://user-images.githubusercontent.com/21367674/122792503-d144e480-d2ec-11eb-9dcb-17f9521e7ed8.png)
sdk版本：
![image](https://user-images.githubusercontent.com/21367674/122792612-e752a500-d2ec-11eb-9f10-3200ed9ddbff.png)

**Comment by frisktale** [comment]
openapi.json的内容是这里存下来的
https://editor.swagger.io/

**Comment by xljiulang** [comment]
这个是一个bug,你可以先传入本地文件的相对路径试试

**Comment by frisktale** [comment]
> 这个是一个bug,你可以先传入本地文件的相对路径试试

相对路径是成功的

**Comment by xljiulang** [comment]
已经发布新版本
