### ISSUE TITLE
你好，请问在调用WebApiClientCore的api之前怎样拿到最开始的那个请求上下文信息呢

### ISSUE THREAD

**Issue by aabb1212** [dotnetcore/WebApiClient#176]
比如：test1()接口请求内部有api1(),api2()..多个自定义的WebApiClientCore的api，在请求api1()之前怎样拿到最初的接口test1()的上下文信息呢，当前httpcontext已经是api1()相关的了。

**Comment by xljiulang** [comment]
https://github.com/dotnetcore/WebApiClient/blob/master/WebApiClientCore.Abstractions/Contexts/ApiRequestContext.cs#L19

**Comment by aabb1212** [comment]
> https://github.com/dotnetcore/WebApiClient/blob/master/WebApiClientCore.Abstractions/Contexts/ApiRequestContext.cs#L19

继承ApiActionAttribute，在OnRequestAsync方法中ApiRequestContext这个类的ApiAction和HttpContext都是当前自定义的api1()的信息，没有最初的接口【test1()】的信息【test1()是供前端调用的接口，其内部的api1(),api2()是自定义的WebApiClientCore接口】

**Comment by xljiulang** [comment]
你把各类型与方法的伪代码写一下，现在描述不清楚

**Comment by aabb1212** [comment]
public async Task TestRpcCache()  //swagger接口
        {
            var api = ObjFty.Get<ISettingApi>();
            var a = await api.GetSetting(new GetSettingInput());
        }
        
        [RpcCacheCore]
        public interface ISettingApi : IHttpApi
        {
             [HttpGet("api/services/xxx/Setting/GetSetting")]
             ITask<string> GetSetting(GetSettingInput input);
        }
        
         public class RpcCacheCoreAttribute : ApiActionAttribute
          {
              public override Task OnRequestAsync(ApiRequestContext context)
              {
                  //想在这里拿到TestRpcCache()的信息.........
                   return Task.CompletedTask;
              }
          }

**Comment by xljiulang** [comment]
你的这个需求不是webApiClient解决的范畴，而是.net框架的范畴，相关资料是[stackframe](https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.stackframe?view=net-5.0)
