### ISSUE TITLE
你好，咨询下服务间调用时，token传递的问题

### ISSUE THREAD

**Issue by xiatiandegaga** [dotnetcore/WebApiClient#178]
目前用的jwt，请求时header里已经有token了，用webapiclient时，传递token
 public class SignFilterAttribute : ApiActionAttribute
    {

        public override Task OnRequestAsync(ApiRequestContext context)
        {
            var currentHttpContext = ((IHttpContextAccessor)context.HttpContext.ServiceProvider.GetService(typeof(IHttpContextAccessor))).HttpContext;
            var token = currentHttpContext.Request.Headers["Authorization"].ToString();
            context.HttpContext.RequestMessage.Headers.Add("Authorization", token);
            return Task.CompletedTask;
        }
    }

有更好的办法吗？

**Comment by xljiulang** [comment]
就是这样子使用

**Comment by xiatiandegaga** [comment]
> 就是这样子使用

好的，谢谢啊，辛苦。
