### ISSUE TITLE
如何在WebApiClientCore下动态设置IUserApi对应的ITokenApi host参数

### ISSUE THREAD

**Issue by ZhaoYang08** [dotnetcore/WebApiClient#199]
services.AddHttpApi<ITokenApi>();
            services.AddHttpApi<IUserApi>();
            services.AddTokenProvider<IStudyImageApi>(async s =>
            {
                return await s.GetService<ITokenApi>().RequestTokenAsync();
            });
            
            IUserApi可以通过[Uri] string host,来动态设置Host，ITokenApi能否直接继承host参数呢？

**Comment by xljiulang** [comment]
不明白说什么

**Comment by ZhaoYang08** [comment]
就是在接口调用的时候设置ITokenApi 对应的Host服务地址。
IUserApi是可以通过UriAttribute动态设置的，ITokenApi 能否类似

**Comment by xljiulang** [comment]
可以

**Comment by ZhaoYang08** [comment]
麻烦给个指引，谢谢

**Comment by xljiulang** [comment]
你在IUserApi会用了，在ITokenApi上怎么就不会用了

**Comment by ZhaoYang08** [comment]
ITokenApi和IUserApi  是通过AddTokenProvider集成的，真正调用IUserApi的时候不会主动调用ITokenApi

**Comment by xljiulang** [comment]
没错，你这里是调用IStudyImageApi时，执行你的自定义委托逻辑，然后调用到ITokenApi，你的ITokenApi对着IUserApi依葫芦画瓢就好了

**Comment by ZhaoYang08** [comment]
前面写错了，是这样的
services.AddHttpApi<ITokenApi>();
        services.AddHttpApi<IUserApi>();
        services.AddTokenProvider<IUserApi>(async s =>
        {
            return await s.GetService<ITokenApi>().RequestTokenAsync();
        });

**Comment by xljiulang** [comment]
这是啥东东

**Comment by ZhaoYang08** [comment]
前面写错了
services.AddHttpApi<ITokenApi>();
        services.AddHttpApi<IUserApi>();
        services.AddTokenProvider<IUserApi>(async s =>
        {
            return await s.GetService<ITokenApi>().RequestTokenAsync();
        });

**Comment by xljiulang** [comment]
你好好的把问题列出清楚吧

**Comment by ZhaoYang08** [comment]
前面写错了
services.AddHttpApi<ITokenApi>();
        services.AddHttpApi<IUserApi>();
        services.AddTokenProvider<IUserApi>(async s =>
        {
            return await s.GetService<ITokenApi>().RequestTokenAsync();
        });

**Comment by ZhaoYang08** [comment]
services.AddHttpApi<ITokenApi>();
        services.AddHttpApi<IUserApi>();
        services.AddTokenProvider<IUserApi>(async s =>
        {
            return await s.GetService<ITokenApi>().RequestTokenAsync();
        });

**Comment by ZhaoYang08** [comment]
`services.AddHttpApi<ITokenApi>();
        services.AddHttpApi<IUserApi>();
        services.AddTokenProvider<IUserApi>(async s =>
        {
            return await s.GetService<ITokenApi>().RequestTokenAsync();
        });`
        前面写错了

**Comment by xljiulang** [comment]
不管ITokenApi还是IUserApi，都是webApiClient里一视同仁的接口声明，声明方式完全一样，如何声明接口，你要阅读文档
