### ISSUE TITLE
MulitpartFile上传文件的时候，如果知道上传进度呢？

### ISSUE THREAD

**Issue by wang-yulong** [dotnetcore/WebApiClient#203]
MulitpartFile上传文件的时候，如果知道上传进度呢？

**Comment by xljiulang** [comment]
MulitpartFile可以包装你要上传的Stream，会对你的Stream进行Read操作，你可以在你的Stream进行自己计算。

**Comment by wang-yulong** [comment]
明白了  感谢感谢
