### ISSUE TITLE
请求路由为什么会带问号

### ISSUE THREAD

**Issue by wangtaoGitAcc** [dotnetcore/WebApiClient#204]
![image](https://user-images.githubusercontent.com/43662206/165086776-e5b8f086-2451-4e4d-9f15-4f6ee5fcef01.png)

使用：

> WebApiClientCore

> WebApiClientCore.Extensions.NewtonsoftJson

netcore：6.0

`  [HttpHost("https://vroom.hesint.net")]
    public interface ITestAPI : IHttpApi
    {
        [HttpPost("​api/_SMS/SendSMS")]
        [JsonReturn]
        Task<Result> Send([JsonContent] SendSms sendSms);
    }

    public class SendSms
    {
        /// <summary>
        /// 
        /// </summary>
        public List<string> deletedFileIds { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string phone { get; set; }
    }

    public class Result
    {
        /// <summary>
        /// 
        /// </summary>
        public bool success { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int code { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool data { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string message { get; set; }
    }
`

`            services
                 .AddHttpApi<ITestAPI>()
                 .ConfigureHttpApi(ConfigRoot.GetSection(nameof(ITestAPI)))
                 .ConfigureHttpApi(o =>
                 {
                     // 符合国情的不标准时间格式，有些接口就是这么要求必须不标准
                     o.JsonSerializeOptions.Converters.Add(new JsonLocalDateTimeConverter("yyyy-MM-dd HH:mm:ss"));
                     o.UseLogging = true;

                 });
`

`  "ITestAPI": {
    "HttpHost": "http://localhost:8075/",
    "UseParameterPropertyValidate": false,
    "UseReturnValuePropertyValidate": false,
    "JsonSerializeOptions": {
      "IgnoreNullValues": true,
      "WriteIndented": false
    }
  }`

**Comment by xljiulang** [comment]
一般是你复制了肉眼不可见的字符路径导致的，你可以复制到文件，使用二进制编辑器查看路径，或者完整手写输入路径看看

**Comment by wangtaoGitAcc** [comment]
手敲还是带问号，我是从我自己写的一个接口进入，然后用webapiClient请求另一个自己写的接口。我最近不能研究了，我这里工期比较吃紧，我决定用HttpClient写
