### ISSUE TITLE
接口状态异常，Content-Type和预期不一样时，无法捕获ApiResponseStatusException

### ISSUE THREAD

**Issue by Ramoshuai** [dotnetcore/WebApiClient#210]
背景：
接口正常响应的content-type是application/json，当遇到异常时候返回是text/plain。

ApiReturnAttribute 的OnResponseAsync，是否应该把ValidateResponseAsync 放在IsMatchAcceptContentType 之前，当状态码异常的时候，此时如果EnsureSuccessStatusCode=true，那么throw ApiResponseStatusException。

不然目前IsMatchAcceptContentType校验的时候返回了 false ，直接return了，到DefaultApiActionInvoker throw new ApiReturnNotSupportedExteption。

我知道是因为我接口返回的content-type类型和预期的不一致导致的，但是当状态码异常的时候，我更多的期望是直接抛出一个ApiResponseStatusException，目前我暂时通过EnsureMatchAcceptContentType设置为false来维持异常捕获的正常使用

```
        public async Task OnResponseAsync(ApiResponseContext context)
        {
            var dataType = context.ActionDescriptor.Return.DataType;
            if (dataType.IsRawType == true)
            {
                return;
            }

            var response = context.HttpContext.ResponseMessage;
            if (response == null)
            {
                return;
            }
            //是否可以放在这里
            await this.ValidateResponseAsync(context).ConfigureAwait(false);

            var contenType = response.Content.Headers.ContentType;
            if (contenType != null
                && this.EnsureMatchAcceptContentType
                && this.IsMatchAcceptContentType(contenType) == false)
            {
                return;
            }

            await this.SetResultAsync(context).ConfigureAwait(false);
        }
```

**Comment by xljiulang** [comment]
为了应对多种响应内容类型，框架将一个接口的返回类型处理设计为有多个apireturn特性来处理，每个特性一般针对一种contentype进行处理。所以最终的逻辑，就成了先contentype匹配，进入特性想然再特性里面判断状态码

**Comment by Ramoshuai** [comment]
> 为了应对多种响应内容类型，框架将一个接口的返回类型处理设计为有多个apireturn特性来处理，每个特性一般针对一种contentype进行处理。所以最终的逻辑，就成了先contentype匹配，进入特性想然再特性里面判断状态码

理想状态下，响应的contentype是要和预期的一致，但是实际情况下，可能网关，或者其他不标准的返回，会存在我上面描述的情况，假如网关不允许访问，他只会简单的返回一个状态码，contentype并不会给你设置成json之类的，这样的话，我们实际捕获的异常就会是ApiReturnNotSupportedExteption，而会忽略真正的状态码异常

**Comment by xljiulang** [comment]
你可以自己实现一个SpecialReturnAttribute子类用于单独处理这个场景，然后把它修饰到你的接口。

**Comment by Ramoshuai** [comment]
嗯嗯，多谢
