### ISSUE TITLE
KeyValueSerializer会在部分字符前面加\

### ISSUE THREAD

**Issue by Ramoshuai** [dotnetcore/WebApiClient#211]
在KeyValueSerializer的GetKeyValueList方法中，System.Text.Json.JsonSerializer.Serialize(utf8JsonWriter, obj, objType, jsonOptions)，虽然使用了JavaScriptEncoder.UnsafeRelaxedJsonEscaping，官方描述，与默认编码器相比，UnsafeRelaxedJsonEscaping 编码器在允许字符通过而不进行转义方面更加宽松。
部分字符转换的时候还是会被加上`\`，如  `<p>\r\n</p>`， 序列化后的字符串为 `<p>\\r\\n</p>`。
在之前使用WebApiClient.JIT/AOT的时候，并没有这个问题出现。看了下之前JIT是用Newtonsoft.json 自定义的一个KeyValuePairConverter来实现key-value的转换，直接取了value的值
请问在core这个版本有办法处理这个问题吗？
目前我暂时通过自定义的Attribute来标记Context，用了原来JIT里面KeyValuePairConverter的转换方法

**Comment by bakapiano** [comment]
同，使用 FormField 自己构造 Post Body 解决了；望 Fix

**Comment by bakapiano** [comment]
@xljiulang

**Comment by xljiulang** [comment]
问题已修复。之前读取文本类型的字段时，没有使用转义导致的问题。
