### ISSUE TITLE
用HttpResponseMessage接受返回时，接口返回404会触发异常

### ISSUE THREAD

**Issue by Ramoshuai** [dotnetcore/WebApiClient#212]
目前可以通过特性[RawReturn( EnsureSuccessStatusCode =false)] 跳过校验。
是否可以智能一点，在RawReturnAttribute 的SetResultAsync 中，如果ApiAction.Return.DataType是HttpResponseMessage的时候，直接跳过状态码校验

**Comment by EzrealJ** [comment]
你好，针对你的提议，你可以自行实现ReturnAttribute来实现，你所提议的“如果ApiAction.Return.DataType是HttpResponseMessage的时候，直接跳过状态码校验”看起来是一个会影响行为一致性的破坏性变更，暂时应该不会考虑。

**Comment by Ramoshuai** [comment]
> 你好，针对你的提议，你可以自行实现ReturnAttribute来实现，你所提议的“如果ApiAction.Return.DataType是HttpResponseMessage的时候，直接跳过状态码校验”看起来是一个会影响行为一致性的破坏性变更，暂时应该不会考虑。

在JIT的版本中，HttpResponseMessage返回的时候，是跳过校验的。因为HttpResponseMessage实际已经包含了状态码。不同于其他

**Comment by EzrealJ** [comment]
虽然你的提议“如果`ApiAction.Return.DataType`是`HttpResponseMessage`的时候，直接跳过状态码校验”看起来合理，但在WebApiClientCore版本中，验证状态码是一个已存在既定的一致性行为，如果对其进行处理，需要考虑将其作为bug或者新特性，是否要兼容当前行为。

需要考虑的问题是，必然存在用户发现这一特点，并进行了相相应处理，直接修改其行为可能会对他们造成一些影响，需要 @xljiulang 参与讨论。
