### ISSUE TITLE
net6+增加全局默认timeout怎么设置哈，现在接口都是默认100秒超时

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/WebApiClient#213]
大佬。如上 之前issue中的timeout的全局设置方案，在net6中要怎么用哈。我没找到对应的方法

**Comment by xljiulang** [comment]
参考
https://learn.microsoft.com/zh-cn/dotnet/api/system.net.http.httpclient.timeout?view=net-7.0

**Comment by yangbocheng** [comment]
谢谢回复。httpclient设置timeout是有所了解的。 
问题在于使用者不看源码是不知道组件的httpclient从哪里获取的，那么对它进行设置就不知道从哪里入手。组件在api中好像没有暴露出容易设置的方法。

**Comment by yangbocheng** [comment]
感觉这样就可以设置每个接口的默认http参数了，不知道对不对。
还想请教作者。如果如下设置以后，一般业务上也没有必要再使用TimeoutAttribute是吧
```csharp
public interface IAuthServer:IHttpApi
...
builder.Services.AddHttpClient(HttpApi.GetName(typeof(IAuthServer)), c =>
{
    c.Timeout = TimeSpan.FromMinutes(3);
});


```

**Comment by xljiulang** [comment]
services.AddHttp<TApi>().ConfigureHttpClient()方法里面配置HttpClient

**Comment by yangbocheng** [comment]
谢谢 明白了
