### ISSUE TITLE
如何设置请求http版本？

### ISSUE THREAD

**Issue by ldqk** [dotnetcore/WebApiClient#216]
如何设置http协议请求为http2？

**Comment by xljiulang** [comment]
参见
https://learn.microsoft.com/zh-cn/dotnet/api/system.net.http.httpclient.defaultrequestversion?view=net-7.0

**Comment by ldqk** [comment]
HttpClient.DefaultRequestVersion不是静态字段啊，得实例化一个HttpClient啊，随便实例化一个HttpClient设置http2，WebApiClient能生效？
