### ISSUE TITLE
特性JsonTent问题

### ISSUE THREAD

**Issue by JoraNoe** [dotnetcore/WebApiClient#219]
WebApiClient.HttpApiException: 执行CreateBatchInvoiceNew出现JsonSerializationException异常
 ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Data.Data', line 1, position 79.  
这是错误内容， 使用 Newtonsoft.Json 没有任何问题  
用JsonContent特性 就弹出这个错误，线上环境 Linxu Docker

**Comment by EzrealJ** [comment]
Duplicate Issue
