### ISSUE TITLE
全局拦截器改变访问接口返回值的问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#22]
我实现IApiActionAttribute接口,想通过拦截访问接口时候出现500,401状态的时候,改变接口返回值
` public Task OnEndRequestAsync(ApiActionContext context)
        {
            if(context.ResponseMessage.StatusCode==HttpStatusCode.InternalServerError)
               context.Result="报错啦"
            return Task.CompletedTask;
        }`

但是我发现context.Result是只读属性,然而我看到IApiReturnAttribute接口,我实现了,但是
config.GlobalFilters.Add方法却只能添加实现IApiActionAttribute接口的类,请问IApiReturnAttribute具体怎么使用

**Comment by xljiulang** [comment]
1、Contentxt的Result值只能由IApiReturnAttribute来影响，简单的，可以从ApiReturnAttribute或AutoReturnAttribute派生，这些都是特性，修饰在接口或方法之上就有效。
2、处理异常，还可以使用ITask<T>.Retry()和ITask<T>Handle()扩展方法来结合。
