### ISSUE TITLE
JsonContent 特性问题 

### ISSUE THREAD

**Issue by JoraNoe** [dotnetcore/WebApiClient#221]
WebApiClient.HttpApiException: 执行CreateBatchInvoiceNew出现JsonSerializationException异常
 ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Data.Data', line 1, position 79.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

**Comment by EzrealJ** [comment]
你好，这这通常意味着你的JSON和接收反序列化结果的类不能匹配，通常您需要仔细比对您的Host、Api、HttpMethod、参数列表来确定错误的地方。
* 另外，你提问的方式非常低效，希望下次您能清楚且高效的描述您的场景并提出您的问题

**Comment by EzrealJ** [comment]
long time no reply
