### ISSUE TITLE
是否支持失败重试+自定义重试策略

### ISSUE THREAD

**Issue by PandaCuipp** [dotnetcore/WebApiClient#226]
目前，接口请求失败后，是否支持重试次数的设置，以及重试频次的设定；
如果没有，是否有这方面的计划

**Comment by EzrealJ** [comment]
你好，请参阅文档
https://webapiclient.github.io/guide/retry.html

**Comment by EzrealJ** [comment]
结合异常处理章节的内容可以处理更多场景
https://webapiclient.github.io/guide/exception-process.html

**Comment by PandaCuipp** [comment]
谢谢，使用Retry可以解决我的问题。麻烦的是我需要在每个IHttpApi被调用的地方加相同的Retry代码。
有没有全局统一加Retry的方案 (^_^)

**Comment by EzrealJ** [comment]
WebApiClientCore 本身是HttpClient的增强  所以你仍然可以使用Microsoft.Extensions.Http.Polly 配置HttpClient的重试，这并不影响WebApiClientCore ，你可以参阅Microsoft.Extensions.Http.Polly的文档

**Comment by PandaCuipp** [comment]
感谢
