### ISSUE TITLE
.net 7.0的Console程序提示不支持将ContentType为 text/html 的内容转换为对象

### ISSUE THREAD

**Issue by ntluojianlin** [dotnetcore/WebApiClient#229]
.net 7.0的Console程序提示不支持将ContentType为 text/html 的内容转换为对象，我加了[JsonReturn]也不行，是需要什么特殊配置吗？

**Comment by xljiulang** [comment]
你可以先阅读文档

**Comment by EzrealJ** [comment]
https://webapiclient.github.io/guide/deformed-interface.html#%E5%93%8D%E5%BA%94%E6%9C%AA%E6%8C%87%E6%98%8E-contenttype

**Comment by ntluojianlin** [comment]
谢谢，弄好了
