### ISSUE TITLE
是否支持HTTPS API

### ISSUE THREAD

**Issue by sharper** [dotnetcore/WebApiClient#23]
是否支持HTTPS ? 
我们请求https的API服务, 会报错
System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("LibreSSL/2.0.20").
   at WebApiClient.ApiTask.ApiTaskOf`1.<RequestAsync>d__6.MoveNext()

**Comment by Yon2068** [comment]
这个问题.netcore官方给了简易是升级为2.1，在2.1忽略了证书的问题。

**Comment by IssacYoung2013** [comment]
.net framework 是否支持 https 访问 api
