### ISSUE TITLE
WriteLog方法BUG。

### ISSUE THREAD

**Issue by vicenteyu** [dotnetcore/WebApiClient#234]
logger.LogInformation在多层级参数转JSON的情况下输出会丢失个别的 “}” 。

![LZU(EHQ{IZK1KP$X8LU7JQ](https://github.com/dotnetcore/WebApiClient/assets/1539280/19fdb4ea-64b3-4c19-8431-ee3f26e9bc58)

重写为下述方法之后，显示结果正常。

`logger.LogInformation("{info}", logMessage.ToString())
`

**Comment by EzrealJ** [comment]
请提供一份demo供我们复现和排查

**Comment by vicenteyu** [comment]
应该是 serilog 消息中间件的设计问题 导致，这个问题可以关闭了 ：） [issues#1631](https://github.com/serilog/serilog/issues/1631)

**Comment by vicenteyu** [comment]
应该是 serilog 消息中间件的设计问题 导致，这个问题可以关闭了 ：）
serilog-issues-1631
