### ISSUE TITLE
请问 HttpApiClient.Create<T>() 还支持吗？

### ISSUE THREAD

**Issue by shiyl962** [dotnetcore/WebApiClient#237]
如题，需要如文章：1.1 最简单的Get请求[#](https://www.cnblogs.com/kewei/p/8295261.html#3445596550)

public interface MyWebApi : IDisposable
{
    // GET http://www.mywebapi.com/webapi/user?account=laojiu
    [HttpGet("http://www.mywebapi.com/webapi/user")]
    ITask<string> GetUserByAccountAsync(string account);
}

var myWebApi = HttpApiClient.Create<MyWebApi>();
var userStr = await myWebApi.GetUserByAccountAsync("laojiu");
myWebApi.Dispose();

来调用此库，但找不到 HttpApiClient.Create<T>() ，请问 HttpApiClient.Create<T>() 还支持吗？
盼复，谢谢！

**Comment by EzrealJ** [comment]
你好，`WebApiClientCore`仅支持依赖注入环境下使用，老版本`WebApiClient.Jit`支持这种形式的使用，详情参考文档https://webapiclient.github.io/，新老版本文档都包含
