### ISSUE TITLE
支持添加自定义请求头吗？

### ISSUE THREAD

**Issue by sanshi2018** [dotnetcore/WebApiClient#241]
接入第三方服务，第三方服务需要在header上添加多个签名字段
第三方服务：[WPS3签名算法说明](https://open.wps.cn/docs/signature/wps-3)

**Comment by EzrealJ** [comment]
你需要动态的请求头？可以先查看文档

**Comment by sanshi2018** [comment]
> 你需要动态的请求头？可以先查看文档
@EzrealJ 
是的，请求头内容需要根据body内容动态生成。
好的 我再仔细看下文档

**Comment by EzrealJ** [comment]
这种你可能需要自定义拦截器或者自定义参数特性来实现

**Comment by EzrealJ** [comment]
这种你可能需要自定义拦截器或者自定义参数特性来实现

**Comment by sanshi2018** [comment]
> 这种你可能需要自定义拦截器或者自定义参数特性来实现

okkk  我懂你意思了
