### ISSUE TITLE
重写IsUnauthorizedAsync读取Body判断Status

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#243]
对方返回值是经典的`{"status":401, "msg":"未验证", "data":{}}`格式，所以在重写IsUnauthorizedAsync方法时需要先反序列化一次读取status的值进行判断。直接读取会导致后续接口获取返回值时第二次读取HttpResponseMessage.Content报错 流已消费。

增加` await response.Content.LoadIntoBufferAsync();`将Content放入内存缓存可解决此问题。
完整代码如下
```csharp
protected override async Task<bool> IsUnauthorizedAsync(HttpResponseMessage response)
{
    await response.Content.LoadIntoBufferAsync();
    var r = await response.Content.ReadFromJsonAsync<VsBaseResult<object>>();
    return r is { Status: 401 };
}
```

这样读取和反序列化两次性能上就弱了些，如何优化

**Comment by EzrealJ** [comment]
我大致理解你是重写了AuthorizationHandler的IsUnauthorizedAsync，来覆盖HttpClient的授权状态，当前你遇到的问题是需要读取两次Body？

**Comment by LGinC** [comment]
是的
