### ISSUE TITLE
KeyValueSerializer 中能否增加对枚举类型转换器的考虑？

### ISSUE THREAD

**Issue by xiaoxiaotank** [dotnetcore/WebApiClient#265]
当定义了如下API接口时，在url中type参数为枚举名称而不是数字，如 type=normal，期望结果：type=1
```csharp
[HttpGet]
Task<TaskDto> GetAsync([PathQuery] TaskType type)
```
通过 [KeyValueSerializer.Serialize](https://github.com/dotnetcore/WebApiClient/blob/master/WebApiClientCore/Serialization/KeyValueSerializer.cs#L44) 方法，可以看到枚举类型直接被 ToString() 了（因为普通枚举的TypeCode为Int32），从而导致值就是枚举值的名字而不是数字

或者有其他实现方式吗？

**Comment by xiaoxiaotank** [comment]
目前已知的一种实现方式是将参数封装为类，可以达到目的，不过上面所提到的可以考虑一下（比如通过特性什么的）

**Comment by xljiulang** [comment]
当前你可以自定义特性，继承PathQueryAttribute并重写`IEnumerable<KeyValue> SerializeToKeyValues(ApiParameterContext)`方法，在里面特殊处理枚举类型的参数

**Comment by xiaoxiaotank** [comment]
> 当前你可以自定义特性，继承PathQueryAttribute并重写`IEnumerable<KeyValue> SerializeToKeyValues(ApiParameterContext)`方法，在里面特殊处理枚举类型的参数

好的，这已经完全能够解决我的问题了，谢谢！
