### ISSUE TITLE
尝试使用WebApiClientCore.OpenApi.SourceGenerator生成支付宝V3 SDK失败

### ISSUE THREAD

**Issue by ZUOXIANGE** [dotnetcore/WebApiClient#267]
是否考虑增强这个功能,当前我对[支付宝V3](https://opendocs.alipay.com/open-v3/054kaq?pathHash=b3eb94e6) SDK使用[openapi-generator](https://github.com/OpenAPITools/openapi-generator)生成的结果并不满意,正在寻找方案尝试重新生成一个SDK

**Comment by xljiulang** [comment]
swagger json链接是多少

**Comment by ZUOXIANGE** [comment]
[openapi.yaml](https://github.com/alipay/alipay-sdk-java-all/blob/master/v3/api/openapi.yaml) 目前应该不支持yaml格式,所以要自己转为json格式

**Comment by xljiulang** [comment]
只支持json格式输入

**Comment by ZUOXIANGE** [comment]
我知道啊,所以我转换为了json格式,同样会报错

**Comment by xljiulang** [comment]
这个问题是注释内容包含了xml保留字符，现在已经做xml字符转义处理：see 
https://github.com/dotnetcore/WebApiClient/commit/50459cb1227e37f6de0b238ba5b6969e9943abaf

工具包已发布，你其更新版本即可

**Comment by ZUOXIANGE** [comment]
现在不报错了,但是生成的代码命名风格不是C#推荐的风格
![image](https://github.com/user-attachments/assets/30e64b31-cfaa-4d4d-ab04-297ac13af1ff)
![image](https://github.com/user-attachments/assets/08dd293b-3555-46a7-96c6-83294238f3ce)

**Comment by xljiulang** [comment]
风格我建议还是保留与官网一致，查阅文档时会更明确。
你可以自己修改cshtml模板，做类型名称变换生成自己的客户端代码，只要变换后的类型名称不冲突即可。
