### ISSUE TITLE
版本2.1.4依赖的Microsoft.Extensions.Caching.Memory 8.0.0包含漏洞，请尽快升级

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#269]
[高危2级漏洞](https://github.com/advisories/GHSA-qj66-m88j-hmgj)

**Comment by EzrealJ** [comment]
你好，你提出的问题我们已经在 [commit a1b2c3d](https://github.com/dotnetcore/WebApiClient/commit/2725ef8e293379ea0a5c9b88a2119b6d349c67d8).进行修复。
不过我们暂时没有发布新的版本😁。
对于当前的`2.1.4`版本,你可以在使用项目中显式依赖更高版本的`Microsoft.Extensions.Caching.Memory`来规避这个问题,最终使用的版本以bin目录下的文件版本为准
