### ISSUE TITLE
当前源码报错

### ISSUE THREAD

**Issue by wjkhappy14** [dotnetcore/WebApiClient#27]
找不到接口XXXXAPIs.IAccount的代理类，请为接口所在项目重新使用Nuget安装WebApiClient.AOT 0.1.0.0

这个需要怎么解决？
请指教！

**Comment by xljiulang** [comment]
不能在项目中直接引用WebApiClient.AOT的程序集，只能使用nuget包安装WebApiClient.AOT的引用

**Comment by wjkhappy14** [comment]
嗯，那我想调试源码，深入学习，逐步调试，该怎么弄呢？

**Comment by xljiulang** [comment]
使用JIT_Debug配置，就可以调试

**Comment by wjkhappy14** [comment]
Demo没法跑起来啊，报错，同样的错误！

**Comment by xljiulang** [comment]
切换配置之后，可能需要重启vs
