### ISSUE TITLE
FormDataContent V2.14版本生成报文bug

### ISSUE THREAD

**Issue by Harbour8643** [dotnetcore/WebApiClient#270]
![image](https://github.com/user-attachments/assets/13e74204-8adb-4fb0-9c4b-08e540b643a2)

ids为空集合情况下：

V2.0.4版本的生成如下：
![image](https://github.com/user-attachments/assets/aa566168-72ef-4e0f-8395-0ed5a3fe6e70)

而V2.1.4版本生成如下：
![image](https://github.com/user-attachments/assets/84d40db4-accb-4758-ac0f-6dad5e492b09)

是否为bug？，这会导致一些库在解析FormDataContent类型请求时报错。

**Comment by Harbour8643** [comment]
![image](https://github.com/user-attachments/assets/ad2b969a-da9f-4e41-86bc-9fdbea3c35cd)
在V2.14版本，当集合为空时，也会创建FormDataContent；

**Comment by EzrealJ** [comment]
已收到你的反馈，我们正在验证
