### ISSUE TITLE
找不到接口Trade.HttpService.IAccount的代理类

### ISSUE THREAD

**Issue by wjkhappy14** [dotnetcore/WebApiClient#29]
System.TypeLoadException:“找不到接口Trade.HttpService.IAccount的代理类，请为接口所在项目重新使用Nuget安装WebApiClient.AOT 0.1.1.0”

请教，该怎么搞？

**Comment by wjkhappy14** [comment]
已经安装了最新的WebApiClient

**Comment by xljiulang** [comment]
更新或手动安装所支持vs的最新版本nuget，确保项目在编译时输出窗口看到如下：
