### ISSUE TITLE
跟MvvmCross不兼容

### ISSUE THREAD

**Issue by liaowubinf** [dotnetcore/WebApiClient#30]
在wpf+mvvmcross 中只要有类继承IHttpApi, 就会导致运行时无法显示界面, 也不报错.....  这问题找了我老半天... 把IhttpApi继承去掉界面就显示了, 求解,  就用MvvmCross官方的Demo试一下

**Comment by xljiulang** [comment]
不相关的类，不需要继承IHttpApi，IHttpApi是WebApiClient的http接口约定而存在的，本质是IDisposable接口。

**Comment by liaowubinf** [comment]
我的意思是MvvmCross项目根本就没法用WebApiClient呀,  定义了任何的HttpApi就会导致Wpf程序启动时无法显示主界面...

**Comment by xljiulang** [comment]
是WebApiClient.JIT包吗，只要定义继承HttpAp的接口，还没有调用就遇到这个现象？

**Comment by liaowubinf** [comment]
是的, 没有任何调用, JIT和AOT都试过了

**Comment by liaowubinf** [comment]
https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc

**Comment by liaowubinf** [comment]
我就用这个例子 https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc, 只要管wpf项目, 其它不用管,
在Core层声明一个测试的IHttpApi实现, 发现只要有IHttpApi的代码, 主界面就出不来了,  但是进程是在的, 任务管理器里面能看到...

**Comment by liaowubinf** [comment]
问题解决了, 不是WebApiClient的问题,  是.net Standard 引入方式的问题, 抱歉大家!
解决方案: https://www.cnblogs.com/podolski/p/8988683.html
