### ISSUE TITLE
HttpApiConfig属性HttpHost设置问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#31]
如果HttpHost设置为http://1.1.1.1:8080访问没有问题,但是现在WEBAPI做了API网关了,路径相应改成http://1.1.1.1/XXX来对应http://1.1.1.1:8080
这是时候如果HttpHost设置为http://1.1.1.1/XXX就会报错,不能正确访问API

**Comment by xljiulang** [comment]
HttpHost是绝对路径就得到支持， 最终是由 HttpHost的绝对路径和接口的相对路径合成接口的最终请求URL，有关URL的合成表示，大概如下：
http://localhost/xx + /yy/zz  = http://localhost/yy/zz
http://localhost/xx + yy/zz  = http://localhost/xx/yy/zz

**Comment by bao2314483** [comment]
经过我测试,我发现URL合成是这样的
**http://localhost/xx/ + yy/zz = http://localhost/xx/yy/zz**
跟你说的不太一样

**Comment by xljiulang** [comment]
哪里不一样，这是我说的第二条规则啊

**Comment by bao2314483** [comment]
你第二条是
http://localhost/xx + yy/zz = http://localhost/xx/yy/zz
实际是
http://localhost/xx/ + yy/zz = http://localhost/xx/yy/zz

少了一个/,而且这个/不能缺少,缺少就url就会变成http://localhost/yy/zz
