### ISSUE TITLE
HttpGet无法支持实体类中包含另一个实体类的情况

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/WebApiClient#32]
比如一个用户类，用户里面又有其他类，就直接将其他类中的字段变为用户类的字段了

实际想要的：http://localhost:50005/api/zh-CN/v1/CrudActions/test?Request.BrandName=444&Request.Status=1&PageIndex=1&PageSize=100
目前的：http://localhost:50005/api/zh-CN/v1/CrudActions/test?BrandName=444&Status=1&PageIndex=1&PageSize=100

可以看到Request这个类名被忽略了，导致服务端无法接收到数据

**Comment by xljiulang** [comment]
WebApiClient的key-value序列化目前不支持嵌套类型的层次分隔

**Comment by hzr1348** [comment]
好像也不支持a=1&a=2这种数组方式的

**Comment by xljiulang** [comment]
数组是支持的

**Comment by hzr1348** [comment]
自己改写了下，仅供参考
`IEnumerable<KeyValuePair<string, string>> PathQueryKeyValuePair(PropertyContractResolver resolver, object value, string prefix)
        {
            if (value == null) yield break;

            Type base_type = value.GetType();
            var base_contract = resolver.ResolveContract(base_type);
            var members = resolver.GetMembers(base_type);
            if (base_contract is Newtonsoft.Json.Serialization.JsonObjectContract base_obj_contract)
            {
                foreach (var sub in base_obj_contract.Properties)
                {
                    var sub_type = sub.PropertyType;
                    var sub_value = sub.ValueProvider.GetValue(value);
                    var sub_contract = resolver.ResolveContract(sub_type);

                    if (sub_contract is Newtonsoft.Json.Serialization.JsonObjectContract objContract)
                    {
                        var sub_value_enumerbale = PathQueryKeyValuePair(resolver, sub_value, prefix + sub_type.Name + ".");
                        foreach (var en in sub_value_enumerbale)
                        {
                            yield return en;
                        }
                    }
                    else if (sub_contract is Newtonsoft.Json.Serialization.JsonArrayContract sub_arrayContract)
                    {
                        Array sub_array = (sub_value as Array);
                        foreach (var arr in sub_array)
                        {
                            yield return new KeyValuePair<string, string>(prefix + sub.PropertyName, arr?.ToString());
                        }
                    }
                    else
                    {
                        yield return new KeyValuePair<string, string>(prefix + sub.PropertyName, sub_value?.ToString());
                    }

                }
            }
        }`

**Comment by hzr1348** [comment]
嗯，但是json和xml描述的目前好像都是body方面的，我不想获取数据的时候用POST请求，只想用GET请求
