### ISSUE TITLE
支持通过 Swagger 文档生成调用客户端，以及服务发现

### ISSUE THREAD

**Issue by poweryang1990** [dotnetcore/WebApiClient#35]
Hi 
WebApiClient 是一个很好的开源项目 我很喜欢其设计思维，用起来很方便，我想 如果我们能够通过Swagger生成客户端 这将会更棒了，这样很好的和其他语言提供的API很好的进行融合调用

另外 可以考虑增加服务发现配置的 Atrribute，以及在创建代理访问实现的时候 增加一些常用的客户端负责算法，通过服务发现的配置来找到对应的服务，
像 Spring Cloud Feign 这类

**Comment by xljiulang** [comment]
WebApiClient具有很强的的可扩展性，像服务发现配置的 Atrribute，除了在库里原生添加支持之外，开发者也可以在项目中自行实现并使用这个功能的特性；2是本项目欢迎开发者们pull request，只要作者觉得Ok的，就合并过来。
关于Swagger，我觉得这个不是WebApiClient需要做，可以创建新的一个工具，负责Swagger to WebApiClient Interface Codes比较合适。

**Comment by xljiulang** [comment]
@poweryang1990 
现在swagger工具应该出来了：
https://github.com/xljiulang/WebApiClient.Tools
