### ISSUE TITLE
配合Hangfire使用问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#37]
我不知道作者你对Hangfire使用过没有,如果没有,你可以百度下,其实作用跟mq非常相似
那问题来了,因为WebApiClient使用接口来写访问api,导致Hangfire异步处理的时候没有办法找到对应接口的实例化类,不知道有什么解决办法
`[HttpHost("http://localhost:60708")]
    public interface web1 : IHttpApi
    {
        [HttpGet("/api/Values")]
        ITask<string> Get();
    }

    public class webtest {
        public web1 web1 => HttpApiClient.Create<web1>();
    }`

控制器
`[HttpGet("Test")]
        public async Task<string> Test()
        {
            BackgroundJob.Enqueue<webtest>(x=> x.web1.Get());
            return "";
        }`

错误提示:The type `WebApiClientTest.web1` must be derived from the `WebApiClientTest.webtest` type.
 Parameter name: type

这是Demo,不要在意细节,因为WebApiClient和Hangfire都是非常好用的插件来,我希望两者能无缝衔接

**Comment by xljiulang** [comment]
你可以试试使用WebApiClient.AOT这个包

**Comment by bao2314483** [comment]
我是试了一下，发现aspnetcore项目引用WebApiClient.AOT这个就依赖项全部有黄色感叹号
错误提示严重性	代码	说明	项目	文件	行	禁止显示状态
错误提示：找不到文件编译输出的程序集

**Comment by xljiulang** [comment]
编译一下，就不提示了

**Comment by bao2314483** [comment]
你这样子是没有问题的，但是你把
`public class HomeController : Controller
{
    public IActionResult Index()
    {
        Hangfire.BackgroundJob.Enqueue<xx>(x => x.web.GetAsync());
        return View();
    }
 }`

`public class xx
    {
        pubilc IWeb1  web=HttpApiClient.Create<IWeb1>();
    }`

这样子就有问题了

**Comment by xljiulang** [comment]
这个跟WebApiClient没有关系呢，应该是Hangfire的局限
