### ISSUE TITLE
调用百度API问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#39]
API路径是这样的 http://api.map.baidu.com/geocoder/v2/?address=北京市海淀区上地十街10号&output=json&ak=您的ak&callback=showLocation

`[HttpGet("/geocoder/v2/")]
        ITask<GeoCoderResult> GeoCoder(GeoCoderRequest ReqData);`
最后生成了 
 http://api.map.baidu.com/geocoder/v2?address=北京市海淀区上地十街10号&output=json&ak=您的ak&callback=showLocation

少了个/,请问怎么设置

**Comment by xljiulang** [comment]
这是一个BUG

**Comment by xljiulang** [comment]
已经提交修复的代码
