### ISSUE TITLE
请求数组有误问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#41]
访问接口定义
`[HttpPost("api/Province/GetList")]
        ITask<ResultList<Province>> GetList([MulitpartContent]ProvinceListReq ReqData);`

` public class ProvinceListReq
    {
        public string[] ProvinceId { get; set; }
        public string PId { get; set; }
        public string PName { get; set; }
        public ProvinceType? Ptype { get; set; }
    }`

请求(这是我代码,不要在意)
`var plist = await this.Remote.Comm.Province.GetList(new ProvinceListReq() {
                        Ptype= ProvinceType.Province
                    });`

然后API那边接收参数发现
ProvinceId的值会变成数组里面多了一个null
意思就是ProvinceId[0]的值是null,这样明显是错的,因为我没有传,ProvinceId应该是null

**Comment by xljiulang** [comment]
你可以把 string[] ProvinceId 从ProvinceListReq 分离出来，作为另一个参数：[MulitpartContent(IgnoreWhenNull = true)] string[] provinceId

或者，在你的ProvinceListReq类的构造器里，将ProvinceId被为0个元素的空数组。

**Comment by bao2314483** [comment]
Ok明白
