### ISSUE TITLE
HttpStatusCode超过1000会报错

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/WebApiClient#42]
服务器提交了协议冲突. Section=ResponseStatusLine

**Comment by xljiulang** [comment]
Http1.1定义了100-505的状态码，HttpClient在实现的时候，约束了状态码的范围为[0-999]，不在范围内的就认为是服务端不遵循http，并默认将[20-299]的状态码解释为成功的状态。简单说，HttpStatusCode是由http定义的，不是业务上可以自行随便增加定义的。

**Comment by hzr1348** [comment]
嗯，明白了，谢谢
