### ISSUE TITLE
api调用这里能否不用必须都写接口？

### ISSUE THREAD

**Issue by ghd258** [dotnetcore/WebApiClient#45]
我们一般都在数据仓储或者业务服务写接口 ，调用api层不写接口，你这个本来是为了方便调用api的 但是必须写接口比较麻烦

**Comment by xljiulang** [comment]
可能是你理解错了，在没有WebApiClient的情况下，请求一个远程http api，你可能要写10行30行代码，完成uri和请求内容的包装、响应的解析等等，但在WebApiClient的情况下，请求一个远程http api不再需要这些具体的代码，而是声明一个接口，里面包含一个方法就行，这个接口不用你来实现。

**Comment by ghd258** [comment]
但是我们不需要接口

**Comment by xljiulang** [comment]
@ghd258 我不关注你们系统是怎么做的，或者是否有需要使用WebApiClient，这个需要你们评估。WebApiClient的理念和安卓的retrofit是一样的。

**Comment by ghd258** [comment]
我也是站在用户的角度给您提个建议 ，你不接受就算了，你这个强制必须申明接口就是比较麻烦，
类似这样的封装调用更为简单，方便用户，可以用接口也可以不用接口
` public static async Task<BaseResult> CallService(string url, object parms, string token = null)
        {
            BaseResult result = null;
            string serviceHost = ConfigurationManager.AppSettings["api_url"];
            string serviceAuth = ConfigurationManager.AppSettings["api_auth"];
            string secretKey = ConfigurationManager.AppSettings["SecretKey"];
            try
            {
                //构建客户端对象
                RestClient client = new RestClient(serviceHost);
                //构建请求，getAppUrl请求地址
                RestRequest request = new RestRequest(url, Method.POST);
                //设置请求头部参数
                request.AddHeader("Authorization", "basic " + serviceAuth + ';' + token);
                request.AddJsonBody(parms);
                //获取返回值
                var _result = await client.ExecutePostTaskAsync(request); 

                result = JsonConvert.DeserializeObject<BaseResult>(_result.Content);
                return result;

            }
            catch (Exception ex)
            {
                result.Code = 100001;
                result.Message = "调用API错误:" + ex.Message;
                return result;
            }

        }`

**Comment by xljiulang** [comment]
这个太低级太耦合了，还是面向过程和指令的，类似于okHttp，webApiClient不作网络请求的底层，其底层是HttpClient，它要做的是retrofit，是httpClient的上层的高度抽象包装，其表达的是你想要什么，而不是你要怎么做，可能你现在领会不到。

**Comment by ghd258** [comment]
好吧，我用这个RestClient 就可以了，您的这个太高级了

**Comment by ghd258** [comment]
你说的解耦是非常好 ，但是我就是调用下远程的api，非得本地定义一套接口，有必要吗？这种情况下不一定是解耦了

**Comment by alexinea** [comment]
然而我说的并不是解耦。

**Comment by hnwywwh** [comment]
有接口适用性更广，越大的项目，越复杂的项目，越需要多人协作的项目，对接口的需求（准确来说对抽象的需求）越迫切




Sent from Mail Master
在2018年09月25日 09:50，AlexLEWIS 写道：

然而我说的并不是解耦。

**Comment by hnwywwh** [comment]
如果项目不大，自己把httpclient稍微封装下足够用了，但是注意下，httpclient创建开销较大，频繁使用注意重用问题还有UseProxy的问题




Sent from Mail Master
在2018年09月26日 11:04，ellison_wu@126.com 写道：
有接口适用性更广，越大的项目，越复杂的项目，越需要多人协作的项目，对接口的需求（准确来说对抽象的需求）越迫切




Sent from Mail Master
在2018年09月25日 09:50，AlexLEWIS 写道：

然而我说的并不是解耦。

**Comment by ghd258** [comment]
尤其是调用第三方api，本来直接调用就可以，但是这种强制必须本地先定义调用api的接口，多谢一些代码，如果不是强制可以根据实际情况需要接口写接口，不需要就直接调用api

**Comment by gebiWangshushu** [comment]
先别急着怼作者；
你发的那个RestClient和HttpPClient看起来没有本质的区别（看起来是，不是很熟悉RestClient）；
那这样你用RestClient时，为了调一个api还是需要写很多行代码，比如构建参数、配置请求、解析响应等；那这样你一般都会封装成一个函数；
现在，这个作者要求声明的这个接口其实就是你封装的这个函数的实体类了。

还有个小建议，提出问题的时候，先不要站在“我这样的看法是正确的“的立场作为出发点。
有点啰嗦，打扰~

**Comment by ghd258** [comment]
你说的对 ，肯定会对RestClient封装一个函数，这样我只是封装一次，不需要每个api写一次的，也行是我不理解，作者现在的这个如果也可以封装一次接口那也不错，不至于对每个调用的api写一个接口吧

**Comment by xljiulang** [comment]
@ghd258 你需要的是HttpClient，发送内容是HttpRequestMessage对象，响应内容是HttpResponseMessage对象，发送方法是SendAsync方法，你还折腾这么久。

**Comment by MissGoing** [comment]
建议把代码拉下来改造一下，给你整开源就是这么玩的
