### ISSUE TITLE
Timeout问题

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/WebApiClient#48]
调用方设置超时时间为3分钟，被调用方执行时间小于3分钟，调用方会报超时错误，大概100秒左右超时，难道是HttpClient本身不能支持超过100秒的超时时间？

**Comment by hzr1348** [comment]
也就是说我这么设置 [Timeout( 3* 60 * 1000)]无效？只要超过100秒就超时了
实际测试就是只要Timeout设置超过100s就会在100s的时候直接终止响应
要怎么做才能超过100s?

**Comment by hzr1348** [comment]
分析了下源码，可能是由于HttpClient中的Timeout属性未设置，我看到TokenClient中有设置该属性
而ApiActionContext中ExecRequestAsync中却没有

**Comment by hzr1348** [comment]
也就是说，我看您源码中使用的是 cancellation.Token，超时时间设置超过100s是无效的。但是我单独设置HttpClient中的Timeout属性就是正常的。

**Comment by hzr1348** [comment]
所以我的问题是，要怎么设置才能让超时时间超过100s呢？

**Comment by izanhzh** [comment]
目前的这个Timeout特性容易产生一种误解，我一开始以为设置这个Timeout就是HttpClient请求的超时时间，然后我有一个需要长时间等待的请求发现怎么设置都不行

**Comment by xljiulang** [comment]
没有好的思路来解决，除非在配置里默认设置HttpClient的Timeout为Timeout.InfiniteTimeSpan

**Comment by hzr1348** [comment]
目前我的解决方案就是以当前HttpClient实例为一个节点，将节点的Timeout对外公布配置，注明所有超过此配置的值失效，作为一种明面上规范去让业务开发人员知道，不然经常会有人问为什么设置不行。
按照正常来说，我传入值的优先级要大于默认设置值，这里有点怪怪的
要么我们的使用HttpClient的超时方式不正确，要么就是它这里设置逻辑有点问题

如果后面我找到更好的方式解决该问题我会重开这个Issue

**Comment by xljiulang** [comment]
@izanhzh 你可以仿照TimeoutAttribute和Timeout写一个就行了，实现为修改Context.HttpApiConfig.HttpClient.Timeout属性。但这个也不是完美的办法，因为这个Timeout是全局的，在并发下修改有可能某个请求的Timeout还是不正确的。

**Comment by xljiulang** [comment]
@hzr1348 我本来想从继承HttpClient来实现，但可重写的方法不够达到这个目标

**Comment by xljiulang** [comment]
目前只能在Timeout特性里增加值范围检测，用于运行时异常抛出：
if (this.TimeSpan > context.HttpApiConfig.HttpClient.Timeout)
{
    throw new HttpApiConfigException($"Timeout值{this.TimeSpan}不能超时HttpApiConfig.HttpClient.Timeout");
}
