### ISSUE TITLE
升级到v0.2.7版本后，与Extensions项目有冲突

### ISSUE THREAD

**Issue by catcherwong** [dotnetcore/WebApiClient#49]
使用版本信息

WebApiClient.Extensions.HttpClientFactory 1.2.3
WebApiClient.JIT 0.2.7

WebApiClient.JIT从0.2.3升级到0.2.7后就有下面的提示了

![tim 20181114165249](https://user-images.githubusercontent.com/8394988/48611614-9dc9ad00-e9c1-11e8-845f-da80ef3357d0.png)

扩展项目的命名空间与Extensions这个类有冲突。

https://github.com/dotnetcore/WebApiClient/blob/JIT/AOT_V0.2.7/WebApiClient/Extensions.cs

**Comment by xljiulang** [comment]
确实，类型与空间冲突

**Comment by catcherwong** [comment]
升级到0.2.8后没有这个问题了。
