### ISSUE TITLE
怎么设置header

### ISSUE THREAD

**Issue by the404** [dotnetcore/WebApiClient#50]
每个请求都要发送固定的header，怎么设置?

**Comment by xljiulang** [comment]
在接口上打特性，或在HttpApiConfig里给HttpClient配置

**Comment by alexinea** [comment]
以下是接口打特性的例子

```c#
public class AppendHeaderAttribute : ApiActionAttribute {
    public override Task BeforeRequestAsync(ApiActionContext context) {
        context.RequestMessage.Headers.TryAddWithoutValidation("ContentType", "application/json;charset=utf-8");
        return Task.CompletedTask;
    }
}
```

[文档地址](https://github.com/dotnetcore/WebApiClient/wiki/WebApiClient%E9%AB%98%E7%BA%A7#21-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%A8%E5%B1%80%E8%BF%87%E6%BB%A4%E5%99%A8)

**Comment by LGinC** [comment]
同一个请求，有些时候需要Authorizator头，有时候不需要，根据请求的参数来决定，这种怎么弄？感觉有点儿反潮流.....

**Comment by xljiulang** [comment]
```
public class AppendHeaderAttribute : ApiActionAttribute {
    public override Task BeforeRequestAsync(ApiActionContext context) {
        context.RequestMessage.Headers.TryAddWithoutValidation("Authorizator", "Basic base64");
        return Task.CompletedTask;
    }
}
```
如同以上逻辑，参数可以从context.ApiActionDescriptor.Parameters[index].Value]读取作为是否需要Authorizator的依据

**Comment by LGinC** [comment]
特性支持依赖注入吗，获取token的方法实现自请求本身(一个请求参数为"getToken"的请求得到的)，token再通过redis缓存获取到的，所以不依赖注入完全拿不到token

**Comment by xljiulang** [comment]
HttpApiConfig支持传入IServiceProvider对象以支持依赖注入，在ApiActionContext对象提供GetService方法从ServiceProvider获取服务实例。如果在asp.net core环境中，使用WebApiClient.Extensions.DependencyInjection或WebApiClient.Extensions.HttpClientFactory扩展项目，默认已经自动设置ServiceProvider实例，只需要在特性相关方法里，调用 context的GetService方法就行。

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/54900271-96855380-4f0d-11e9-94a9-d82e4377c460.png)
搞定，thx

**Comment by xljiulang** [comment]
@LGinC 如果你的token接口与本接口分开，可以使用GetService获取token接口；如果是同一个接口里面，那么context的HttpApi属性就是接口本身的实例，就也是token接口实例。

**Comment by LGinC** [comment]
稍微用缓存封装了一下，因为token不需要经常获取，所以还是得GetService

**Comment by LGinC** [comment]
@xljiulang 
![image](https://user-images.githubusercontent.com/15363011/54900602-db5dba00-4f0e-11e9-8e7c-15a9fa682693.png)
关于时间格式，我传入的是DateTimeOffset会不会生效？

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/54900637-faf4e280-4f0e-11e9-91e5-43537c2ce4bb.png)
