### ISSUE TITLE
请求输出到控制台失败

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#54]
![image](https://user-images.githubusercontent.com/15363011/53471772-b9ece800-3aa0-11e9-9d25-97e4a77918ac.png)

![image](https://user-images.githubusercontent.com/15363011/53471877-12bc8080-3aa1-11e9-92b6-b8d8010c7095.png)

![image](https://user-images.githubusercontent.com/15363011/53471797-d2f59900-3aa0-11e9-866e-395034c5d9c6.png)

“ConsoleLoggerExtensions.AddConsole(ILoggerFactory)”已过时:“This method is obsolete and will be removed in a future version. The recommended alternative is AddConsole(this ILoggingBuilder builder).”

控制台并没有输出请求

**Comment by xljiulang** [comment]
这里是HttpApiFactory的误用造成的，你的IOvoparkApi应该是从HttpApiFactory创建的，而不是使用HttpApiCilient创建的。

**Comment by LGinC** [comment]
warning CS0618: '“ConsoleLoggerExtensions.AddConsole(ILoggerFactory)”已过时:“This method is obsolete and will be removed in a future version. The recommended alternative is AddConsole(this ILoggingBuilder builder).”
