### ISSUE TITLE
aspnetcore2.1新增集成测试需求,能有HttpClient注入方式

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/WebApiClient#55]
以下是aspnetcore集成测试文档
https://docs.microsoft.com/zh-cn/aspnet/core/test/integration-tests?view=aspnetcore-2.2

里面WebApplicationFactory来运行要测试的aspnetcore项目,但是多各项目之间我是通过WebApiClient来互相调用的,但是集成测试只是暴露了HttpClient来访问接口,WebApiClient缺少配置HttpClient的方法,导致所有接口为了适应测试,都要自己实现一遍,工作量非常大,看能不能有一个注入方式注入HttpClient到WebApiClient里面去

**Comment by xljiulang** [comment]
```
var httpClient = new HttpClient()或外部HttpClient;
var httpApiConfig = new HttpApiConfig(httpClient)
{
    ....
};           
var client = HttpApiClient.Create<TInterface>(httpApiConfig);
```

**Comment by bao2314483** [comment]
在这个扩展里面WebApiClient.Extensions.HttpClientFactory如何注入HttpClient呢?

**Comment by xljiulang** [comment]
HttpClientFactory的HttpClient肯定是由HttpClientFactory自己创建维护的，而不是从外部实例注入进来。但是HttpClient实例化时可以传入其依赖的HttpMessageHandler实例，HttpClientFactory提供ConfigurePrimaryHttpMessageHandler方法配置HttpMessageHandler。所以流程是：HttpClientFactory注入外部的HttpMessageHandler，然后创建HttpClient，再传入WebApiClient。

**Comment by bao2314483** [comment]
WebApiClient.Extensions.DependencyInjection 可以注入HttpClient吗?

WebApiClient.Extensions.DependencyInjection与WebApiClient.Extensions.HttpClientFactory有什么区别哦
