### ISSUE TITLE
后期是否有支持http/2的计划？

### ISSUE THREAD

**Issue by bingzheaaa** [dotnetcore/WebApiClient#56]
如题！

**Comment by xljiulang** [comment]
WebApiClient底层依赖于HttpClient，HttpClient的.net core环境未来将支持http2，corefx下已经有HttpClient的http2协议实现的初期代码。

**Comment by xljiulang** [comment]
https://github.com/dotnet/corefx/tree/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HPack
