### ISSUE TITLE
.Net 4.7 下调用，报错

### ISSUE THREAD

**Issue by hazihazi123** [dotnetcore/WebApiClient#58]
通过nuget下载的 Laojiu.WebAppClient 1.2.2
.Net 4.5 使用时正常，升级到.Net 4.7 后调用报错
System.Exception:“找不到方法:“System.Net.Http.HttpResponseMessage WebApiClient.Contexts.ApiActionContext.get_ResponseMessage()”。”
看源码预编译是.Net 4.5 的，是否有其他童鞋在4.7下使用过？

**Comment by xljiulang** [comment]
使用WebApiClient.JIT包看看，Laojiu.WebAppClient这个已经不维护了
