### ISSUE TITLE
时间格式序列化

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#59]
`services.AddHttpApiTypedClient<IOvoparkApi>(c =>
            {
                c.LoggerFactory = new LoggerFactory().AddConsole();
                c.FormatOptions.DateTimeFormat = "yyyy-MM-dd HH:mm:ss";
            });`
![image](https://user-images.githubusercontent.com/15363011/54901327-17921a00-4f11-11e9-8a10-7ac3ab550312.png)
一人血书求支持DateTimeOffset日期格式设置

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/54901431-650e8700-4f11-11e9-895e-d36d1507c8be.png)

**Comment by xljiulang** [comment]
本来就支持DateTimeOffset啊，你可以自己试试。不管是使用DateTimeFormatAttribute还是设置FormatOptions.DateTimeFormat都生效。

**Comment by LGinC** [comment]
好像是哦，没注意urldecode解码结果............
