### ISSUE TITLE
autofac如何进行批量注入

### ISSUE THREAD

**Issue by cheetahing** [dotnetcore/WebApiClient#60]
文档里提供的autofac的注入方式是这样的
builder.Register(_ => new HttpApiFactory<IMyWebApi>()
    .ConfigureHttpApiConfig(c =>
    {
        c.HttpHost = new Uri("http://localhost:9999/");
        c.FormatOptions.DateTimeFormat = DateTimeFormats.ISO8601_WithMillisecond;
    }))
    .As<IHttpApiFactory<IMyWebApi>>()
    .SingleInstance();

builder.Register(c => c.Resolve<IHttpApiFactory<IMyWebApi>>().CreateHttpApi())
    .As<IMyWebApi>()
    .InstancePerHttpRequest();

希望根据包扫描自动的注入所有的接口，我的有两个想法
一、提供HttpApiFactory的重载给使用者自已实现扫包，自已注入，需要这样的重载方法
 HttpApiFactory(Type type)
使用时是这样的
new HttpApiFactory(typeof(IMyWebApi))
或new HttpApiFactory(type)

二、提供autofac扫包的扩展方法
通过包扫描出所有继承于IHttpApi接口，然后批量注入到容器里。
autofac的扩展后，能过调用方法就能自动注入，类似于以下用法
builder.RegisterAssemblyTypes(Assembly.GetCallingAssembly()).AsImplementedIHttpApi()
**重点在于AsImplementedIHttpApi()**，自动扫包自动注入

**Comment by xljiulang** [comment]
上面贴出的代码实现，可以理解为一个RegisterApi<TInterface>()的泛型方法，当存在N个TInterface的Type时，可以反射RegisterApi生成N种对应的RegisterApi<NInteface>方法，然后调用生成的RegisterApi<NInteface>()就可以了。

**Comment by xljiulang** [comment]
代码思路如下，在泛型RegisterApi方法里包装单个强类型在autofac的注射，非泛型RegisterApi方法包装调用泛型的RegisterApi方法：

```c#
static void RegisterApi(Type @interface, object builder)
{
    var registerApi = typeof(Program).GetMethod("RegisterApi").MakeGenericMethod(@interface);
    registerApi.Invoke(null, new[] { builder });
}


static void RegisterApi<TInterface>(object builder) where TInterface : IHttpApi
{
    // autofac register code
}
```

**Comment by cheetahing** [comment]
非常感谢，已经解决了，完整的代码贴在下面
PS:同名的静态方法无法反射，已经改为另一个名字

        public static void RegisterApiByType(Type @interface, object builder)
        {
            var registerApi = typeof(AutofacModuleRegister).GetMethod("RegisterApi").MakeGenericMethod(@interface);
            registerApi.Invoke(null, new[] { builder });
        }


        public static void RegisterApi<TInterface>(ContainerBuilder builder) where TInterface : class,IHttpApi
        {
            builder.Register(p => new HttpApiFactory<TInterface>()
               .ConfigureHttpApiConfig(c =>
               {
                   c.HttpHost = new Uri("http://localhost:51606/");
                   c.FormatOptions.DateTimeFormat = DateTimeFormats.ISO8601_WithMillisecond;
               }))
               .As<IHttpApiFactory<TInterface>>()
               .SingleInstance();

            builder.Register(c => c.Resolve<IHttpApiFactory<TInterface>>().CreateHttpApi())
                .As<TInterface>()
                .InstancePerLifetimeScope();
        }

**Comment by xljiulang** [comment]
OK，同一种原理另一种方法是，在泛型类里的非泛型方法实现注册，然后传入interface type创建泛型类，将实例转换为其注册方法声明的对应接口来调用完成注册

**Comment by xljiulang** [comment]
[WebApiClient.Extensions.Autofac](https://github.com/xljiulang/WebApiClient.Extensions/blob/master/WebApiClient.Extensions.Autofac/HttpApiFactoryBuilder.cs#L28)已经出来，你可以参考一下

**Comment by cheetahing** [comment]
非常感谢！准备投入生产项目中使用
