### ISSUE TITLE
1.0.3 HttpHost配置不生效

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#63]
![image](https://user-images.githubusercontent.com/15363011/56090786-81cb2880-5ed9-11e9-9c33-e9a724f19ea1.png)

ERROR 2019-04-14 17:18:05,957 [34   ] Mvc.ExceptionHandling.AbpExceptionFilter - 未配置HttpHost，无法应用路径/gettoken
WebApiClient.HttpApiConfigException: 未配置HttpHost，无法应用路径/gettoken
   at WebApiClient.Attributes.HttpMethodAttribute.GetRequestUri(Uri baseUri, Uri relative)
   at WebApiClient.Attributes.HttpMethodAttribute.BeforeRequestAsync(ApiActionContext context)
   at WebApiClient.Contexts.ApiActionContext.PrepareRequestAsync()
   at WebApiClient.Contexts.ApiActionContext.ExecuteActionAsync[TResult]()
   at WebApiClient.ApiTask`1.InvokeAsync()

**Comment by LGinC** [comment]
.net core 2.2
使用WebApiClient.Extensions.HttpClientFactory配置依赖注入
![image](https://user-images.githubusercontent.com/15363011/56090813-d1a9ef80-5ed9-11e9-9dc7-262421ababc8.png)

**Comment by xljiulang** [comment]
看看你配置的代码，还有获取Api实例的代码

**Comment by LGinC** [comment]
![image](https://user-images.githubusercontent.com/15363011/56090850-38c7a400-5eda-11e9-85f7-57743b679e74.png)
![image](https://user-images.githubusercontent.com/15363011/56090860-454bfc80-5eda-11e9-8d8d-175fffb906f1.png)
![image](https://user-images.githubusercontent.com/15363011/56090866-49781a00-5eda-11e9-9f6b-15dcb8d0943e.png)
![image](https://user-images.githubusercontent.com/15363011/56090872-56950900-5eda-11e9-910d-306cbade6196.png)

**Comment by LGinC** [comment]
上个版本是没问题的，升级到1.0.3后才出的错

**Comment by xljiulang** [comment]
你贴上代码吧，今天github图片资源挂了

**Comment by LGinC** [comment]
`[TraceFilter]
    [HttpHost("https://oapi.dingtalk.com")]
    public interface IDingTalkApi : IHttpApi
    {
        /// <summary>
        /// 获取访问令牌
        /// </summary>
        /// <param name="corpid">企业Id</param>
        /// <param name="corpsecret">企业密钥</param>
        /// <returns></returns>
        [HttpGet("/gettoken")]
        ITask<AccessToken> GetAccessToken(string corpid, string corpsecret);`

API定义


` services.AddHttpApiTypedClient<IWeChatAPI>(c =>
            {
                if (DebugHelper.IsDebug) c.LoggerFactory = new LoggerFactory().AddConsole();
                c.FormatOptions.DateTimeFormat = "yyyy-MM-dd HH:mm:ss";
            });`

配置依赖注入


 private IDingTalkApi Client { get; set; }
     
        public DingTalkAppService(IHostingEnvironment env,
                                  IDingTalkApi dingTalkApi,)
        {
            configuration = env.GetAppConfiguration();
            Client = dingTalkApi;
        }

public async Task<string> GetAccessToken()
        {
            string corpid = configuration["Authentication:DingTalk:AppKey"];
            string corpsecret = configuration["Authentication:DingTalk:AppSecret"];
            var result = await Client.GetAccessToken(corpid, corpsecret);
            if (result.Errcode != 0) Logger.Error($"Current AppKey:{corpid} AppSecret:{corpsecret}");
            result.CheckError("GetAccessToken");
            return result.Access_token;
        }

**Comment by LGinC** [comment]
不对，降级了也没用，应该同一时间升级的其他nuget导致的

**Comment by xljiulang** [comment]
是1.03的问题，已[提交修复](https://github.com/dotnetcore/WebApiClient/commit/9e65c72d758b7947df7d506713e0e49b52a9190f)

另外，使用了WebApiClient.Extensions.HttpClientFactory，就不用设置LoggerFactory，这个会自动从ServiceProvider获取，而ServiceProvider默认已经赋值。

**Comment by xljiulang** [comment]
你当前可以跳过不使用[HttpHostAttribue]，把域名配置到 c.HttpHost= your host

**Comment by LGinC** [comment]
OK，谢谢
