### ISSUE TITLE
请求添加一个不进行日志输出的标注

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#70]
比如有一个api接口集合里有10个api，其中9个需要进行日志输出，1个是高频调用，无需日志输出。
现有的TraceFilter标注针对整个api集合，而且是输出，所以还需要一个针对方法的标注，作用为不输出

**Comment by xljiulang** [comment]
所有Filter都有Enable属性，在不需要输出的方法上设置TraceFilter的Enable为false即可

**Comment by LGinC** [comment]
thanks
