### ISSUE TITLE
批量注入IHttpApi接口

### ISSUE THREAD

**Issue by itachijames** [dotnetcore/WebApiClient#73]
verson 1.1.0
在`ConfigureServices(IServiceCollection services)`里批量注入继承`IHttpApi`的接口，目前做法是反射出所有接口，再逐个添加：
````
foreach (var api in externalApis)
{
    services.AddSingleton(api, HttpApi.Create(api, new HttpApiConfig
    {
        HttpHost = new Uri(_appConfiguration["ExternalApi:Url"])
    }));
}
````
然而这里的Create方法不被推荐使用。是不是可以直接忽略这个warning，还是要Register、Resolve的流程走一波？有没有什么推荐的最佳实践

**Comment by xljiulang** [comment]
可以忽略。最佳是使用[WebApiClient.Extensions.HttpClientFactory](https://github.com/xljiulang/WebApiClient.Extensions)
