### ISSUE TITLE
Polly 集成至WebApiClient Polly策略配置无法生效

### ISSUE THREAD

**Issue by wulaiwei** [dotnetcore/WebApiClient#74]
1.定义策略
            var retryPolicy = HttpPolicyExtensions
             .HandleTransientHttpError()
            .Or<HttpApiException>(x => x.InnerException.GetType() == typeof(HttpRequestException))
            .Or<HttpApiException>(x => x.InnerException.GetType() == typeof(HttpStatusFailureException))
            .Or<TimeoutRejectedException>()
            .Or<Exception>()
            .RetryAsync(2);
2.添加策略
https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory
    return services
                .AddHttpClient<TInterface>()
                **.AddPolicyHandler(retryPolicy)**
                .AddTypedClient((httpClient, provider) =>
                {
                    var httpApiConfig = new HttpApiConfig(httpClient)
                    {
                        ServiceProvider = provider
                    };
                    configOptions.Invoke(httpApiConfig, provider);
                    return HttpApi.Create<TInterface>(httpApiConfig);
                });
3.模拟错误 指定接口抛出默认异常
![image](https://user-images.githubusercontent.com/16910820/62339635-4186c900-b50f-11e9-918a-0ac191a47cd5.png)
  无法执行重试策略

**Comment by xljiulang** [comment]
首先要了解WebApiClient的异常，基类是HttpApiException，然后是子类HttpStatusFailureException和HttpApiConfigException等，其它异常就包装为HttpApiException子内部异常。
WebApiClient返回的ITask`1类型自带Retry功能，所以也可以不需要Polly

**Comment by xljiulang** [comment]
还有，你这里是想用Polly来抓取WebApiClient异常，这是行不通的，Polly控制的是HttpMessageHandler来完成它的策略，WebApiClient是Polly执行完它的策略之后得到HttpReponseMessage了再装配结果和抛出WebApiClient异常。

**Comment by wulaiwei** [comment]
主要是我们想所有接口都完成重试机制，限制版本的Retry好像是只能在方法后面执行Retry 而不能统一执行Retry，之前我们是通过Autofac 注入的时候添加AOP完成的重试机制  但是在高并发下限制提供的Autofac扩展会导致System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed. 如果不将IHttpApiFactory<T> 注入为单例是可以解决上的问题 但是又会导致内存无法释放，所以当前版本我们只能采用AddHttpApiTypedClient方式进行注入

**Comment by xljiulang** [comment]
Polly是在HttpClient层工作的，往上一层一HttpClientFactory，再往上是WebApiClient。这里可以认为Polly是对HttpClientHandler作拦截包装，输出HttpClientMessageHandler给HttpClientFactory来维护Handler的生命周期，WebApiClient将Handler再包装为声明式接口调用。
