### ISSUE TITLE
.net与Java关于URL Encode的区别

### ISSUE THREAD

**Issue by SmallChi** [dotnetcore/WebApiClient#75]
特殊字符：%2C与%2c

.net  客户端
string str = "appId=****2&msgInfo=%230000%2cRbsT&sysSimId=122330&timestamp=***&uuid=**";
var result = getMD5(str); 

java 服务端
string str = "appId=****2&msgInfo=%230000%2CRbsT&sysSimId=122330&timestamp=***&uuid=**";
var result = getMD5(str);

现在目前解决的方式是写个过滤器特性，然后进行url解码，在通过[参考](https://www.cnblogs.com/xinlulicheng/p/9529410.html)这个demo在进行编码最后在进行签名，感觉好low，请问九哥有没有更好的方式。

**Comment by xljiulang** [comment]
可以重启 PathQueryAttribute或FormContentAttribute的相关方法，对value进行自行编码，然后再调用重写方法的base对应方法即可。原理是自行编码过的值，再次编码也不会有变化。

**Comment by SmallChi** [comment]
好的 谢谢九哥 大概知道了
