### ISSUE TITLE
自动补全的Header与ApiActionAttribute设置Header的顺序相关的几个问题

### ISSUE THREAD

**Issue by AlaricGilbert** [dotnetcore/WebApiClient#76]
1、请问自动补全的Header（User-Agent、Host等）的执行顺序是否有固定在自定义的ApiActionAttribute前或后？同为ApiActionAttribute，为什么使用Header自行指定UA和Host可以而使用自己编写的Attribute确依然使用的是默认补全的UA与Host？
2、自动补全Header能否关闭，全由Method指定的ApiActionAttribute或者全局Filter来自行设置？

**Comment by xljiulang** [comment]
在构建请求信息HttpApiRequestMessage的构造器时，自动设置了ExpectContinue和UserAgent请求头，所以在任意可以访问到ApiActionContext的地方，均可自行修改ApiActionContext.RequestMessage.Headers。
