### ISSUE TITLE
接口返回状态码 403时，会抛HttpStatusFailureException异常，影响反序列化返回值

### ISSUE THREAD

**Issue by PandaCuipp** [dotnetcore/WebApiClient#77]
例如：接口定义如下，
ITask<UserResult> Get(int id);

当查询失败时，返回状态码403，内容包含失败的对象，需要反序列化为UserResult,
但是因为抛HttpStatusFailureException异常，导致不能直接调用Get(id)方法获取失败时的结果

该怎么解决？

**Comment by xljiulang** [comment]
两种方式
1、捕获HttpStatusFailureException异常，使用异常的ReadAs相关方法读取内容。
2、为接口或方法设置的[AutoReturn]或[JsonReturn]等ApiReturn特性设置EnsureSuccessStatusCode属性为false，非200-299的返回状态码也不会转换为异常。

**Comment by PandaCuipp** [comment]
谢谢，
之前用的第一种方式，感觉太臃肿；
试了第二种方式，非常好用。
再次感谢您的解答~~
