### ISSUE TITLE
UWP(.Net Standard 2.0) 无法使用 WebApiClient

### ISSUE THREAD

**Issue by Sanlorng** [dotnetcore/WebApiClient#78]
尝试在项目中引入WebApiClient，在使用HttpApi.Resolve() 方法进行接口的初始化时，会抛出 System.Runtime.Caching PlatformNotSupportedException，查阅官方文档和WebApiClient源码，WebApiClient 在ResponseCacheProvider中引用了System.Runtime.Caching命名空间的类，而官方文档中声明UWP，Xarmarin.iOS，.NET Core 2.0 运行时均不包含此命名空间，故不能在相关平台上使用WebApiClient库。

[
![Snipaste_2019-08-11_18-31-43](https://user-images.githubusercontent.com/26089739/62832803-e9666a00-bc66-11e9-8bcf-1dd9dae73297.png)
![Snipaste_2019-08-11_18-31-58](https://user-images.githubusercontent.com/26089739/62832804-e9ff0080-bc66-11e9-84a2-7bf39bcc8ad2.png)
![Snipaste_2019-08-11_18-32-24](https://user-images.githubusercontent.com/26089739/62832805-e9ff0080-bc66-11e9-8dc9-af46048cd561.png)
![Snipaste_2019-08-11_18-34-44](https://user-images.githubusercontent.com/26089739/62832806-ea979700-bc66-11e9-9424-d3197c826426.png)

](url)

**Comment by xljiulang** [comment]
OK，考虑下个版本的AOT移除缓存默认实现。

**Comment by xljiulang** [comment]
新版本已经使用Microsoft.Extensions.Caching.Memory

**Comment by Sanlorng** [comment]
> 新版本已经使用Microsoft.Extensions.Caching.Memory

刚刚测试，已经能用了，感谢
