### ISSUE TITLE
Get请求不支持嵌套对象吗？

### ISSUE THREAD

**Issue by liaowubinf** [dotnetcore/WebApiClient#80]
不如我有个请求参数实体   ParameterA,
`public class ParameterA
{
    public ParameterB B{ get; set; }
}

public class Parameter
{
   public string Test{ get; set; }
}

`
这个时候它生成的url是    ?test=xxx,  而我期望的是  ?b.test=xxx;

这种情况能不能支持呢

**Comment by xljiulang** [comment]
不支持
