### ISSUE TITLE
如何实现外部传入Header的值

### ISSUE THREAD

**Issue by LGinC** [dotnetcore/WebApiClient#81]
![image](https://user-images.githubusercontent.com/15363011/64165272-4e346f00-ce77-11e9-8013-47568dae0eb0.png)
![image](https://user-images.githubusercontent.com/15363011/64165281-52f92300-ce77-11e9-8f39-45b7020cfde4.png)
我选择的方式是通过一个额外的参数来传入，但是不知道怎么能让额外参数不会作为网络请求参数的一部分。(放入请求类里加IgnoreSerialized其实也可以，但就让请求类看起来太不清真了)

**Comment by xljiulang** [comment]
[HeaderAttribute]可用于修饰方法或参数，此处用于修饰参数，用法： [Header("Authorizator")] string appKey

**Comment by LGinC** [comment]
thx
