### ISSUE TITLE
支持Polly 吗 比如熔断

### ISSUE THREAD

**Issue by ghd258** [dotnetcore/WebApiClient#83]
https://github.com/App-vNext/Polly   或者Microsoft.Extensions.Http.Polly

**Comment by xljiulang** [comment]
HttpClientFactory支持Polly，WebApiClient支持HttpClientFactory，通过HttpClientFactory桥梁，支持Polly：
Polly->HttpClientFactory->WebApiClient

**Comment by ghd258** [comment]
有使用的demo例子吗

**Comment by catcherwong** [comment]
@ghd258  可以参考下面的这个例子，

```cs
services.AddHttpApiTypedClient<IDemoApi>(config => { })
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler() { UseProxy = false })
    //fallback       
     .AddPolicyHandler(Policy<HttpResponseMessage>.Handle<Exception>().FallbackAsync((ctx, ct) =>
     {
            return Task.FromResult(new HttpResponseMessage
            {
                Content = new StringContent("fallback"),
                StatusCode = HttpStatusCode.OK
            });
      }, async (b, ctx) =>
      {
          await Task.CompletedTask;
      }));
```

需要添加 `WebApiClient.Extensions.HttpClientFactory` 的引用。

**Comment by ghd258** [comment]
非常感谢 如果能有更详细的demo就更好的 比如怎么设置重试机制，设置降级等

**Comment by catcherwong** [comment]
`AddHttpApiTypedClient`之后，就和 `AddHttpClient`一样了，直接参考Polly提供的文档即可。

https://github.com/App-vNext/Polly/wiki/Polly-and-HttpClientFactory

**Comment by ghd258** [comment]
非常感谢，建议WebApiClient 如果能封装支持Polly 使用起来就更加方便了
