### ISSUE TITLE
Error when API has a relative path

### ISSUE THREAD

**Issue by Tossler** [dotnetcore/WebApiClient#85]
My Application is hosted in a subdirectory, so lets say it's local path is:

http://localhost/myapp/

and api method would then be:

http://localhost/myapp/api/method

when I register the api by 

`
            HttpApi.Register<ISlaApiClient>().ConfigureHttpApiConfig(c =>
            {
                c.HttpHost = new Uri("http://localhost/myapp");
            });
`

and decorate the methods with 

`[HttpGet("/api/method")]`

it doesn't work, i need to register as` c.HttpHost = new Uri("http://localhost"); `and include myapp in the decorator:
`[HttpGet("/myapp/api/method")]`

I have a lot of environments and all have different path, that means I need to create separate api interface for each of them. Is there a way to include the relative path in the hostname?

**Comment by xljiulang** [comment]
well，set c.HttpHost=new Uri("http://localhost/myapp/")
and then with method attribute [HttpGet("api/method")] is what u need.
the full uri is created by new Uri(baseUri, path):
http://localhost/myapp + api/method = http://localhost/api/method
http://localhost/myapp/ + api/method = http://localhost/myapp/api/method
http://localhost/myapp + /api/method = http://localhost/api/method
http://localhost/myapp/ + /api/method = http://localhost/api/method
