### ISSUE TITLE
ITask<R> Retry 再走切面时，上下文为null

### ISSUE THREAD

**Issue by wangzhenalex** [dotnetcore/WebApiClient#87]
重写 HeaderAttribute ，将一个cookie值通过header往三方接口传递。

在第一次调用时 HttpContext.Current 正常
在Retry的时候，HttpContext.Current 为 nulll，CallContext.HostContext 也为null 

![image](https://user-images.githubusercontent.com/8923180/65738775-91e86480-e115-11e9-87b5-0b12d68b6911.png)

**Comment by xljiulang** [comment]
请查阅HttpContext异步环境的相关资料，与本库无关
