### ISSUE TITLE
有时会请求不到数据是怎么回事？

### ISSUE THREAD

**Issue by waleswood** [dotnetcore/WebApiClient#89]
如下图所示，偶尔能请求到数据，大部分情况下都会是这样
![微信截图_20191008175257](https://user-images.githubusercontent.com/3008502/66469179-00d0a080-eaba-11e9-9424-d7f10f095b4e.png)

**Comment by xljiulang** [comment]
图片的数据就是服务端返回的啊

**Comment by waleswood** [comment]
不是的。我用浏览器直接加参数请求，每次都能成功请求到数据。

**Comment by xljiulang** [comment]
你这个图片上的数据也是请求得到啊，又不是客户端异常信息

**Comment by waleswood** [comment]
这就很奇怪了。我用官方的demo，就改了下Get 请求的地址和传入的参数，还是不行，但是用浏览器就能正确返回。
