### ISSUE TITLE
调用api怎么设置Timeout超时

### ISSUE THREAD

**Issue by ghd258** [dotnetcore/WebApiClient#9]
有时候api端方法处理需要很长时间才能完成，ui端调用api就会超时，怎么解决这个问题

**Comment by catcherwong** [comment]
第三种方式，对于新版(v1.0.6)Timeout类型的参数是否要调整成  `WebApiClient.Attributes.TimeoutAttribute`类型 ?

**Comment by xljiulang** [comment]
是的

**Comment by catcherwong** [comment]
用了`WebApiClient.Attributes.TimeoutAttribute`后，生成的请求url貌似多了一些东西。

![diff](https://user-images.githubusercontent.com/8394988/56558031-e3714e00-65cf-11e9-94d9-ae611332ce4b.png)

**Comment by xljiulang** [comment]
让我看一下接口声明

**Comment by catcherwong** [comment]
v1.0.6 的定义如下
```cs
public interface IDemoApi : IHttpApi
{
    [HttpGet]
    ITask<string> QueryAsync([Uri] string url, TimeoutAttribute timeout);
}
```

v0.2.3 的定义如下
```cs
public interface IDemoApi : IHttpApi
{
    [HttpGet]
    ITask<string> QueryAsync([Url] string url, Timeout timeout);
}
```

**Comment by xljiulang** [comment]
TimeoutAttribute timeout 改为[Timeout] int timeout

**Comment by catcherwong** [comment]
可以了 👍

**Comment by ghd258** [comment]
无论你是new一个静态HttpClient还是通过HttpClientFactory去创建HttpClient,记得要将UseProxy=false（当然，除非你要用proxy那就没辙

**Comment by CambridgeYi** [comment]
set Timeout Attribute return Unable to read data from the transport connection: Operation canceled,how solve?

**Comment by CambridgeYi** [comment]
设置 Timeout后，请求有时候会返回 Unable to read data from the transport connection: Operation canceled.，这要怎么能返回超时，而不是这个异常
