### ISSUE TITLE
Post方式提交数据时，怎么设置Content-Type 为text/plain的格式呢

### ISSUE THREAD

**Issue by DeskZq** [dotnetcore/WebApiClient#91]

**Comment by xljiulang** [comment]
使用StringContent做参数

**Comment by Dunxiliao** [comment]
怎么设置默认不加上 charset=utf-8呢？
对方接口：Content-Type: application/json 可以正常返回
Content-Type: application/json;utf-8 或 Content-Type: application/json;charset=uft-8 就会返回415

**Comment by EzrealJ** [comment]
> 怎么设置默认不加上 charset=utf-8呢？ 对方接口：Content-Type: application/json 可以正常返回 Content-Type: application/json;utf-8 或 Content-Type: application/json;charset=uft-8 就会返回415

参数特性允许设置CharSet

**Comment by Dunxiliao** [comment]
使用JsonContent就好了，感谢大佬
