### ISSUE TITLE
按照markdown 进阶 httpclientfactory 报错  net core 3.0 项目

### ISSUE THREAD

**Issue by WuMianRen** [dotnetcore/WebApiClient#94]

**Comment by WuMianRen** [comment]
services.AddHttpClient<IBaiduApi>().AddTypedClient<IBaiduApi>((client, p) =>
            {
                var httpApiConfig = new HttpApiConfig(client)
                {
                    HttpHost = new Uri("http://www.baidu.com/"),
                  
                };
                return HttpApi.Create<IBaiduApi>(httpApiConfig);
            });



System.InvalidOperationException:“The HttpClient factory already has a registered client with the type 'Intelligence.Api.Interface.IBaiduApi'. Client types must be unique. Consider using inheritance to create multiple unique types with the same API surface.”

**Comment by WuMianRen** [comment]
https://github.com/xljiulang/WebApiClient.Extensions
已解决请访问上面地址 
希望作者也可以更新帮助文档中的内容

**Comment by wswind** [comment]
在.net core 3.0中
services.AddHttpClient<IMyWebApi>().AddTypedClient<IMyWebApi>按照wiki配置会提示httpclient重复注册的异常
extension中是通过
```
 return services
                .AddHttpClient(typeof(TInterface).ToString())
                .AddTypedClient((httpClient, provider) =>
                {
                    var httpApiConfig = new HttpApiConfig(httpClient)
                    {
                        ServiceProvider = provider
                    };
                    configOptions.Invoke(httpApiConfig, provider);
                    return HttpApi.Create<TInterface>(httpApiConfig);
                });
```
实现的，无非就是传入type改为了传入string，不知道是不是微软的bug
