### ISSUE TITLE
当请求接口服务器地址是多个时怎么处理比较好

### ISSUE THREAD

**Issue by gjl8820** [dotnetcore/WebApiClient#95]
hi ，当系统请求的接口服务器有多个，这个应该怎么配置，只能用 每个方法添加hot地址吗？

**Comment by xljiulang** [comment]
一套接口多个不同域名服务器？

**Comment by gjl8820** [comment]
不好意思我可能没描述清楚，现在遇到情况是我调用的接口来自多个服务器，是每个服务器写一个iwebapi还是共用一个，在每个方法上添加服务器地址！我现在全局只有一个iwebapi ，针对多个服务器不是很清楚应该怎么写

**Comment by xljiulang** [comment]
同一个域名的接口，可以写在一起，也可以分开写多个。不同域名的接口，肯定是要分开才好，因为域名是可以为一个IHttpApi对象声明的所有请求方法统一配置的。

**Comment by gjl8820** [comment]
我看你教程说最好只有一个全局ihttpapi ，那这样是不是我就需要定义多个ihttpapi 对象，在注入时会有问题吧
