### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by WuMianRen** [dotnetcore/WebApiClient#98]
LoggerFactory = null  实际运行时候 提示日志不能为空
错误信息：
System.ArgumentNullException:“Value cannot be null. ”

**Comment by xljiulang** [comment]
不允许设置Null值

**Comment by WuMianRen** [comment]
解决了  不需要那个东西   直接会自动输出到日志工厂  看了半天文档  -。-

**Comment by WuMianRen** [comment]
谢谢了

**Comment by WuMianRen** [comment]
有个问题就是日志能不能格式化一下在输出到日志工厂    里面有好多转义字符

**Comment by xljiulang** [comment]
继承trackefilterbase自己处理

**Comment by WuMianRen** [comment]
thaank you  速度很快 很赞
