### ISSUE TITLE
When to support .core 3.1?

### ISSUE THREAD

**Issue by andyyi** [dotnetcore/WebApiClient#99]
As the title, when you would fully support this package with .net core 3.x? I upgrade my solution from .net core 2.2 to 3.1. There are lots of issues as below 

1. WebApiClient does support Newtonsoft.Json, while .ent core 3.1 already switch to System.Text.Json. 

2. I guess for the above reason, DateTime is NOT recognized any more when I post the object with datetime into web api, api side would get null.

Looking forward to your answers. Thanks.

**Comment by xljiulang** [comment]
默认的，asp.net core webApi使用 System.Text.Json，且默认配置只支持输入ISO8601的时间格式，所以有两个方法可以解决，方法1：给asp.net core webApiClient增加DateTime的JsonConverter，以支持非ISO8601时间格式；方法2：在把webApiClient的HttpApiConfig.FormatOptions.DateTimeFormat设置为"O"

**Comment by andyyi** [comment]
@xljiulang  Thank you very much, but your proposal does NOT resolve my issue. Probably I didn't get the key point for how to use this setting. But when I add AddNewtonsoftJson after services.AddMVC(), this issue got disappear. Anyway, thank you very much.

**Comment by xljiulang** [comment]
Well,`System.text. Json` only supports the input time format of ISO8601 by default, so you need to configure the interface in WebApiClient with the time format of "O":
```
HttpApi.Register<YourWebApi>().ConfigureHttpApiConfig(c =>
{
     // iso8601 
    c.FormatOptions.DateTimeFormat = "O";
```
